### ISSUE TITLE
[Bug Report]: Wrong output when building ESM file which includes UMD code

### ISSUE THREAD

**Issue by claneo** [web-infra-dev/rspack#2222]
### System Info

System:
OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
CPU: (8) x64 Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
Memory: 7.01 GB / 15.40 GB
Container: Yes
Shell: 5.8 - /usr/bin/zsh
Binaries:
Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
npmPackages:
@rspack/cli: ^0.1.0 => 0.1.0

### Details

When run an app using `monaco-editor`, it reports a runtime error

```
Uncaught TypeError: Cannot set property marked of #<Object> which has only a getter
    at eval (eval at ./node_modules/.pnpm/monaco-editor@0.32.1/node_modules/monaco-editor/esm/vs/base/common/marked/marked.js (main.js:555:1), <anonymous>:1835:25)
    at eval (eval at ./node_modules/.pnpm/monaco-editor@0.32.1/node_modules/monaco-editor/esm/vs/base/common/marked/marked.js (main.js:555:1), <anonymous>:17:72)
    at eval (eval at ./node_modules/.pnpm/monaco-editor@0.32.1/node_modules/monaco-editor/esm/vs/base/common/marked/marked.js (main.js:555:1), <anonymous>:20:7)
    at eval (eval at ./node_modules/.pnpm/monaco-editor@0.32.1/node_modules/monaco-editor/esm/vs/base/common/marked/marked.js (main.js:555:1), <anonymous>:1847:3)
    at ./node_modules/.pnpm/monaco-editor@0.32.1/node_modules/monaco-editor/esm/vs/base/common/marked/marked.js (main.js:555:1)
    at __webpack_require__ (main.js:2296:33)
    at fn (main.js:2429:10)
    at eval (eval at ./node_modules/.pnpm/monaco-editor@0.32.1/node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js (main.js:291:1), <anonymous>:24:17)
    at ./node_modules/.pnpm/monaco-editor@0.32.1/node_modules/monaco-editor/esm/vs/base/browser/markdownRenderer.js (main.js:291:1)
    at __webpack_require__ (main.js:2296:33)
```

### Reproduce Steps

The problem is caused by this file: https://github.com/microsoft/vscode/blob/dea2281013a641b48f01ba703383368009d8968a/src/vs/base/common/marked/marked.js

Minimal reproduce:

```js
// ESM-uncomment-begin
let __marked_exports = {};
(function() {
  function define(deps, factory) {
    factory(__marked_exports);
  }
  define.amd = true;
// ESM-uncomment-end

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.marked = {}));
})(this, (function (exports) { 'use strict';
  exports.foo = 'bar'
  Object.defineProperty(exports, '__esModule', { value: true });
}));

// ESM-uncomment-begin
})();
export var marked = (__marked_exports || exports);
// ESM-uncomment-end
```

The output of rspack includes unexpected variable `exports`

```js
{"./src/lib.js": function (module, exports, __webpack_require__) {
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "marked", {
    enumerable: true,
    get: function() {
        return marked;
    }
});
let __marked_exports = {};
(function() {
    function define(deps, factory) {
        factory(__marked_exports);
    }
    define.amd = true;
    (function(global, factory) {
        typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) : typeof define === 'function' && define.amd ? define([
            'exports'
        ], factory) : (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.marked = {}));
    })(this, function(exports1) {
        'use strict';
        exports1.foo = 'bar';
        Object.defineProperty(exports1, '__esModule', {
            value: true
        });
    });
})();
var marked = __marked_exports || exports;
},}
```

Compare to webpack:

```js
{/***/ "./src/lib.js":
/*!********************!*\
  !*** ./src/lib.js ***!
  \********************/
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "marked": () => (/* binding */ marked)
/* harmony export */ });
// ESM-uncomment-begin
let __marked_exports = {};
(function() {
  function define(deps, factory) {
    factory(__marked_exports);
  }
  define.amd = true;
// ESM-uncomment-end

 (function (global, factory) {
  typeof exports === 'object' && "object" !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.marked = {}));
})(this, (function (exports) { 'use strict';
  exports.foo = 'bar'
  Object.defineProperty(exports, '__esModule', { value: true });
}));

// ESM-uncomment-begin
})();
var marked = (__marked_exports || exports);
// ESM-uncomment-end

/***/ })}
```

**Comment by magic-akari** [comment]
How was this module imported into your code?

Do you have similar logic in your code as below?"

```javascript
import * as ns from "marked";

ns.marker = function() {};
```

Please note that references exported in ESM are immutable.

**Comment by claneo** [comment]
> How was this module imported into your code?

This a file in `monaco-editor`, my code is just:

```js
import * as monaco from 'monaco-editor';`
```

> Do you have similar logic in your code as below?

No

**Comment by underfin** [comment]
This need implement custom runtime to align webpack, it's already in our roadmap, please wait some days.

**Comment by hardfist** [comment]
ping @underfin

**Comment by lyuehh** [comment]
supported after <https://github.com/web-infra-dev/rspack/releases/tag/v0.3.10>

**Comment by ahabhgk** [comment]
Yes, if I remember correctly we have fixed this in before versions, thinks for validate this
