### ISSUE TITLE
[Bug Report]: report Cannot read properties of undefined (reading 'createSignatureFunctionForTransform')

### ISSUE THREAD

**Issue by xwchris** [web-infra-dev/rspack#2262]
### System Info

System:
    OS: macOS 11.7.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 274.13 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.2/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 107.0
    Safari: 16.3.1
  npmPackages:
    @rspack/cli: ^0.1.0 => 0.1.0 

### Details

I have a `rspack.config.js` like this
```js
module.exports = {
 entry: {
    main: './src/index.ts',
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].[contenthash].js',
  },
  builtins: {
    html: [
      {
        template: './src/index.html',
      }
    ]
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        type: 'jsx',
      },
      {
        test: /\.ts$/,
        type: 'tsx',
      },
    ],
  },
  devServer: {
    hot: true
  }
};
```

the `./src/index.ts` content is just `console.log('hello world')`

when use `rspack serve ` to run, will get a `Uncaught TypeError: Cannot read properties of undefined (reading 'createSignatureFunctionForTransform')` error in browser console.

And I tried to remove `module.rules`, it will work well

### Reproduce Steps

1. run `rspack serve`
2. see browser console

**Comment by underfin** [comment]
Can you give a reproduction for this?

**Comment by DoneDeal0** [comment]
I confirm the error. I'm trying RSPack today, but I can't add any rules. The React app only starts if I remove the `rules` entry.

The error is:

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'createSignatureFunctionForTransform')
    at ./node_modules/events/events.js (events.js:6:1)
    at __webpack_require__ (index.tsx:8:1)
    at fn (index.tsx:8:1)
    at ./node_modules/@rspack/dev-client/node_modules/webpack-dev-server/node_modules/webpack/hot/emitter.js (emitter.js:1:1)
    at __webpack_require__ (index.tsx:8:1)
    at fn (index.tsx:8:1)
    at ./node_modules/@rspack/dev-client/node_modules/webpack-dev-server/client/utils/reloadApp.js (reloadApp.js:72:1)
    at __webpack_require__ (index.tsx:8:1)
    at fn (index.tsx:8:1)
    at ./node_modules/@rspack/dev-client/dist/index.js?protocol=ws%3A&hostname=0.0.0.0&port=8080&pathname=%2Fws&logging=info&overlay=%7B%22errors%22%3Atrue%2C%22warnings%22%3Afalse%7D&reconnect=10&hot=true&live-reload=true (index.js:12:1)
```

The `rspack.config.js` looks like this:

```js
/* eslint-env node */
/** @type {import('@rspack/cli').Configuration} */

const path = require("path");

module.exports = {
  context: __dirname,
  entry: {
    main: "./src/index.tsx",
  },
  output: {
    path: path.join(__dirname, "./build"),
    filename: "[name].[contenthash].bundle.js",
    chunkFilename: "[name].chunk.bundle.js",
    publicPath: "/",
  },
  devServer: {
    historyApiFallback: true,
    open: true,
  },
  builtins: {
    html: [
      {
        favicon: path.join(__dirname, "./src/assets/images/favicon.png"),
        template: "./src/index.html",
      },
    ],
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js", "jsx", ".json"],
    alias: {
      api: path.resolve(__dirname, "src/api/"),
      assets: path.resolve(__dirname, "src/assets/"),
      components: path.resolve(__dirname, "src/components/"),
      containers: path.resolve(__dirname, "src/containers/"),
      hooks: path.resolve(__dirname, "src/hooks/"),
      models: path.resolve(__dirname, "src/models/"),
      pages: path.resolve(__dirname, "src/pages/"),
      src: path.resolve(__dirname, "src/"),
    },
    tsConfigPath: "./tsconfig.json",
  },

  module: {
    rules: [
      {
        test: /\.svg$/,
        type: "asset",
      },
      {
        test: /\.js$/,
        type: "jsx",
      },
      {
        test: /\.ts$/,
        type: "tsx",
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        type: "asset/resource",
      },
      {
        test: /^BUILD_ID$/,
        type: "asset/source",
      },
    ],
  },
};

```

How to fix this? I've strictly followed the official documentation.

**Comment by mrrs878** [comment]
I tried to add `module.rules.include`
``` js
{
    test: /\.js$/,
    type: 'jsx',
    include: [/src/, /some other path/]
},
```
And it will work well

**Comment by IWANABETHATGUY** [comment]
> Nice, it works! But the `include: [/src/]` part was not mentioned in the [official documentation](https://www.rspack.dev/guide/react.html), hence the error.
> 
> Thank you for your answer!

`module.rule.include` was mentioned here. https://www.rspack.dev/config/module.html#ruleinclude

**Comment by IWANABETHATGUY** [comment]
Since the issue has been solved, closed. Feel free to reopen this issue if you have any further questions.
