### ISSUE TITLE
[Feature Request]:  compilation.rebuildModule does not exist

### ISSUE THREAD

**Issue by zackarychapple** [web-infra-dev/rspack#2622]
### What problem does this feature solve?

Part of the angular build process below does a second pass on the files in order to inject the compiled html and styles. 
```ts
const rebuild = (webpackModule) => new Promise((resolve) => compilation.rebuildModule(webpackModule, () => resolve()));
```

This is caused by the rebuildModule hook not existing. 
```bash
[rspack-cli] [Error: napi error: GenericFailure - TypeError: compilation.rebuildModule is not a function
    at /Users/packages/ngtools/webpack/src/ivy/plugin.ts:431:52
    at new Promise (<anonymous>)
    at rebuild (/Users/packages/ngtools/webpack/src/ivy/plugin.ts:431:9)
    at /Users/packages/ngtools/webpack/src/ivy/plugin.ts:440:65
    at Array.map (<anonymous>)
    at AngularWebpackPlugin.rebuildRequiredFiles (/Users/packages/ngtools/webpack/src/ivy/plugin.ts:440:42)
    at /Users/packages/ngtools/webpack/src/ivy/plugin.ts:333:7
```

### What does the proposed API of configuration look like?

In order to do a proper full angular build without inline templates we will need this hook.

**Comment by zackarychapple** [comment]
Bumping so it is not marked as stale. I know its still needed and far from stale.
