### ISSUE TITLE
[Bug Report]: [Error: error[internal]: should run render_chunk hook.

### ISSUE THREAD

**Issue by B1anker** [web-infra-dev/rspack#2672]
### System Info

System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.13 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 103.0.2
    Safari: 16.2

### Details

<e> [webpack-dev-middleware] [Error: error[internal]: should run render_chunk hook.
<e> Raw: panicked at 'should run render_chunk hook', /Users/runner/work/rspack/rspack/crates/rspack_plugin_javascript/src/plugin.rs:224:8
<e> This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.
<e> 
<e>    0: _napi_register_module_v1
<e>    1: <unknown>
<e>    2: _napi_register_module_v1
<e>    3: _napi_register_module_v1
<e>    4: _napi_register_module_v1
<e>    5: _napi_register_module_v1
<e>    6: _napi_register_module_v1
<e>    7: _napi_register_module_v1
<e>    8: _napi_register_module_v1
<e>    9: _napi_register_module_v1
<e>   10: <unknown>
<e>   11: <unknown>
<e>   12: <unknown>
<e>   13: <unknown>
<e>   14: <unknown>
<e>   15: <unknown>
<e>   16: <unknown>
<e>   17: <unknown>
<e>   18: _napi_register_module_v1
<e>   19: _napi_register_module_v1
<e>   20: _napi_register_module_v1
<e>   21: _napi_register_module_v1
<e>   22: _napi_register_module_v1
<e>   23: _napi_register_module_v1
<e>   24: _napi_register_module_v1
<e>   25: _napi_register_module_v1
<e>   26: _napi_register_module_v1
<e>   27: _napi_register_module_v1
<e>   28: _napi_register_module_v1
<e>   29: __pthread_deallocate
<e> 
<e> ] {
<e>   code: 'GenericFailure'
<e> }

### Reproduce link

https://github.com/B1anker/rspack_render_chunk_panic.git

### Reproduce Steps

pnpm install
pnpm serve

update any code

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/17514962/230716225-42139f3b-c6d6-4809-af53-d89c8cfadb67.png">

**Comment by shawnmcknight** [comment]
I'm seeing this issue occur if the `target` is set to anything other than `web` (i.e. `browserslist`, `es2021`, etc.).

I tried running the latest nightly as I thought #2744 might solve for it.  The error reported by @B1anker is not being emitted any longer, but instead I am now seeing:

```
thread 'thread 'thread 'thread 'tokio-runtime-workerthread 'thread 'thread 'thread 'thread 'tokio-runtime-workertokio-runtime-workertokio-runtime-workerthread 'thread '' panicked at 'tokio-runtime-worker' panicked at '' panicked at 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'should run render_chunk hooktokio-runtime-workerthread 'should run render_chunk hooktokio-runtime-workerthread 'should run render_chunk hooktokio-runtime-workershould run render_chunk hookthread '' panicked at '' panicked at 'tokio-runtime-worker' panicked at 'tokio-runtime-worker', should run render_chunk hooktokio-runtime-worker' panicked at '', tokio-runtime-worker' panicked at 'D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs', ' panicked at '' panicked at 'should run render_chunk hook' panicked at 'should run render_chunk hookshould run render_chunk hook' panicked at 'should run render_chunk hook', ', ', D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rsshould run render_chunk hook', D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs', D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs:D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rsshould run render_chunk hook::should run render_chunk hookshould run render_chunk hookD:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rsD:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rsD:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs:233:', ', thread '', should run render_chunk hook::', 233thread ':', 233233D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs:233233:', tokio-runtime-worker8D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rstokio-runtime-worker233D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs::' panicked at '::D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rsD:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs:233should run render_chunk hook82338::',
8
233' panicked at '
:D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs
8should run render_chunk hook8::D:\a\rspack\rspack\crates\rspack_plugin_javascript\src\plugin.rs',
:ote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

8233::
8:23388:
833:

[rspack-cli] [Error: error[internal]: should run render_chunk hook.
Raw:
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.


] {
  code: 'GenericFailure'
}
```

**Comment by hardfist** [comment]
you can set `['web','es2021']` to avoid this problem, we need to add check logic to avoid set target to esx without set target to 'web' or 'node' etc, which webpack did
![image](https://user-images.githubusercontent.com/8898718/232396520-876b9fea-0534-40b5-96a8-4906166a8459.png)

**Comment by shawnmcknight** [comment]
>you can set ['web','es2021'] to avoid this problem, we need to add check logic to avoid set target to esx without set target to 'web' or 'node' etc, which webpack did

@hardfist Wouldn't setting it that way defeat the purpose of trying to set `es2021`?  With use of `web`, wouldn't it just downlevel to `es2015` and not provide any support for `es2021`?  It might avoid the error, but I'm trying to understand what benefit it might provide to configure that way.

**Comment by underfin** [comment]
The caused by rspack set chunkLoadingPlugin & chunkFormatPlugin by target platform at previous implement, #2792 will aligin to webpack.

**Comment by hardfist** [comment]
> @hardfist Wouldn't setting it that way defeat the purpose of trying to set `es2021`? With use of `web`, wouldn't it just downlevel to `es2015` and not provide any support for `es2021`? It might avoid the error, but I'm trying to understand what benefit it might provide to configure that way.

no, `web` is used to control `chunkloading` & `chunkFormat` but `esx` is used to control runtime code syntax, so they're seperate options to control different things, it will not cause to downlevel to `es2015` when you set target to [`web`,`es2021`]

**Comment by underfin** [comment]
closed at #2792
