### ISSUE TITLE
Rspack incompatibile with generate-package-json-webpack-plugin

### ISSUE THREAD

**Issue by dgmachado** [web-infra-dev/rspack#2719]
### System Info

System:
OS: macOS 13.1
CPU: (10) arm64 Apple M1 Pro
Memory 32GB
Shell: /bin/zsh

Binaries: 
node: 16.13.2
npm: 9.5.0
yarn: 1.22.19

Browsers:
Chrome: 111.0.5563.146

npmPackages:
@nrwl/rspack: 15.9.5
@rspack/core: ~0.1.0
@rspack/dev-server: ~0.1.0
@rspack/plugin-minify: ~0.1.0

### Details

Rspack seems to be incompatible with the [generate-package-json-webpack-plugin](https://www.npmjs.com/package/generate-package-json-webpack-plugin) package.

It's happening a fatal error:
```
[Error: napi error: GenericFailure - TypeError: compilation.modules is not iterable
```

### Reproduce Steps

1. Create an rspack project
2. Install the generate-package-json-webpack-plugin package: npm i -D generate-package-json-webpack-plugin
3. Add the plugin into the rspack.config.js file:

```
plugins: [
   new GeneratePackageJsonPlugin({}, { useInstalledVersions: true })
],
```

**Comment by dgmachado** [comment]
This plugin is useful for when you have a large source project for development / testing from which smaller Node.js projects are bundled for various deployments and applications. Such as Google Cloud Functions.

Or even just for bundling your regular Node.js server code, and knowing that your package.json is as lean as it can possibly be for that next deployment.

**Comment by dgmachado** [comment]
@IWANABETHATGUY after update my app to use "@rspack/cli": "0.0.0-canary-5be5027-20230425165317" and customized to use the below plugin:

```
plugins: [
    new GeneratePackageJsonPlugin({}, { useInstalledVersions: true })
  ]
```

I'm getting the below error:
```
> rspack build -c rspack.config.js

[rspack-cli] [Error: napi error: GenericFailure - TypeError: compilation.modules is not iterable
    at computePackageJson (/Users/douglasmachado/Documents/Rspack/14-mongoose-base/node_modules/generate-package-json-webpack-plugin/index.js:273:40)
    at emitPackageJson (/Users/douglasmachado/Documents/Rspack/14-mongoose-base/node_modules/generate-package-json-webpack-plugin/index.js:367:18)
    at /Users/douglasmachado/Documents/Rspack/14-mongoose-base/node_modules/generate-package-json-webpack-plugin/index.js:375:15
    at eval (eval at create (/Users/douglasmachado/Documents/Rspack/14-mongoose-base/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:17:1)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/Users/douglasmachado/Documents/Rspack/14-mongoose-base/node_modules/tapable/lib/HookCodeFactory.js:75:10), <anonymous>:6:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/Users/douglasmachado/Documents/Rspack/14-mongoose-base/node_modules/tapable/lib/Hook.js:22:14)
    at Compiler._Compiler_processAssets (/Users/douglasmachado/Documents/Rspack/14-mongoose-base/node_modules/@rspack/core/src/compiler.ts:376:5)
   0: _napi_register_module_v1
   1: <unknown>
   2: <unknown>
] {
  code: 'GenericFailure'
}
```

Any suggestion what could be the root cause of this?

**Comment by IWANABETHATGUY** [comment]
try @nightly
