### ISSUE TITLE
Support @vanilla-extract/webpack-plugin (compiler.hooks.normalModuleFactor, NormalModuleFactory.hooks.createModule missing))

### ISSUE THREAD

**Issue by lalexdotcom** [web-infra-dev/rspack#2845]
### What problem does this feature solve?

Some hooks are missing for compatibility with @vanilla-extract/webpack-plugin (and I suppose other plugins may use them)
Vanilla extract CSS is a build-time css-in-js

I see in the code that some hooks are missing in Compiler and NormalModuleFactory:
- `compiler.hooks.normalModuleFactory`
- `nmf.hooks.createModule.tap`
- _(and `nmf.hooks.afterResolve` for webpack 4, but rspack is seen as Webpack 5)_

### What does the proposed API of configuration look like?

```
const {
  VanillaExtractPlugin
} = require('@vanilla-extract/webpack-plugin');

module.exports = {
  plugins: [new VanillaExtractPlugin()]
};
```

**Comment by zackarychapple** [comment]
After resolve can be connected to #2619

**Comment by lalexdotcom** [comment]
I see this issue is tagged "awaiting more feedback": FMI, what kind of feedback does it need?

**Comment by zackarychapple** [comment]
@lalexdotcom would you mind testing with the latest, there is an underlying issue that was referenced that is already merged. We've also started using NMF with Angular so this issue should be resolved. If you can confirm we can close this issue.

**Comment by lalexdotcom** [comment]
Hey @zackarychapple !

It looks like the `Compiler.hooks.normalModuleFactory` is there now, thanks to the team (and Angular)!

But the `NormalModuleFactory.hooks.createModule`isn't there yet... I think this hook from NormalModuleFactory is not used by Angular...

**Comment by lecstor** [comment]
In case this is the "more feedback" you're looking for, I hit the same issue with a brnad new project over the weekend.

```
[webpack-dev-middleware] [Error: napi error: GenericFailure - TypeError: Cannot read properties of undefined (reading 'tap')
<e>     at /Users/jason/dev/radix-extract/node_modules/@vanilla-extract/webpack-plugin/dist/vanilla-extract-webpack-plugin.cjs.dev.js:173:30
<e>     at Hook.eval (eval at create (/Users/jason/dev/radix-extract/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
<e>     at Hook.CALL_DELEGATE [as _call] (/Users/jason/dev/radix-extract/node_modules/tapable/lib/Hook.js:14:14)
<e>     at Compiler._Compiler_newCompilation (/Users/jason/dev/radix-extract/node_modules/@rspack/core/dist/Compiler.js:771:36)
<e>    0: _napi_register_module_v1
<e>    1: <unknown>
<e>    2: <unknown>
<e> ] {
<e>   code: 'GenericFailure'
<e> }
```

```
"@rspack/cli@npm:latest":
  version: 0.3.0
  resolution: "@rspack/cli@npm:0.3.0"
```

**Comment by hardfist** [comment]
sorry these hooks are difficult to implement now and it may take some time for us to implement

**Comment by felixmosh** [comment]
Same here, `i18next-hmr` requires the `createModule` hook.

**Comment by xc2** [comment]
`compiler.hooks.normalModuleFactory` and `nmf.hooks.createModule` have been shipped in Q1 2024. Please give it a try.
