### ISSUE TITLE
Compilation crashes when using newrelic - InternalError { error_message: "Can't construct regex `/^.*\\/nr\\-hooks$/`"

### ISSUE THREAD

**Issue by antoinepairet** [web-infra-dev/rspack#3241]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 206.14 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 8.19.2 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: 113.0.1774.35
    Safari: 16.4
  npmPackages:
    @rspack/cli: 0.1.11 => 0.1.11 
    @rspack/core: 0.1.11 => 0.1.11 
    @rspack/dev-server: ~0.1.0 => 0.1.11 
    @rspack/plugin-minify: ~0.1.0 => 0.1.11 

### Details

The package `newrelic` cannot be bundled because rspack crashes during the compilation.

The error message is slightly different when using `require` vs `import`, but the root cause is the same.

Using `require`:
````
Error: error[internal]: reg failed: InternalError(InternalError { error_message: "Can't construct regex `/^.*\\/nr\\-hooks$/`", severity: Error }).
Raw: panicked at 'reg failed: InternalError(InternalError { error_message: "Can't construct regex `/^.*\\/nr\\-hooks$/`", severity: Error })', crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs:96:55
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.

   0: _napi_register_module_v1
   1: <unknown>
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: _napi_register_module_v1
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <unknown>
  44: _napi_register_module_v1
  45: _napi_register_module_v1
  46: <unknown>
  47: _napi_register_module_v1
  48: _napi_register_module_v1
  49: _napi_register_module_v1
  50: __pthread_joiner_wake
````

Using `import`:
````
thread 'tokio-runtime-worker' panicked at 'reg failed: InternalError(InternalError { error_message: "Can't construct regex `/^.*\\/nr\\-hooks$/`", severity: Error })', crates/rspack_plugin_javascript/src/visitors/dependency/scanner.rs:96:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: error[internal]: reg failed: InternalError(InternalError { error_message: "Can't construct regex `/^.*\\/nr\\-hooks$/`", severity: Error }).
Raw: 
This is not expected, please file an issue at https://github.com/web-infra-dev/rspack/issues.

````

### Reproduce Steps

Try to compile a file with:

````ts
require('newrelic');
````

OR 

````ts
import newrelic from 'newrelic';
console.log(newrelic);
````

**Comment by antoinepairet** [comment]
🤩 The rspack team is impressively reactive 💯 🙇🏻 🙌🏻 
Thank you @hardfist 💪🏻

**Comment by mciparelli** [comment]
Is this going to fix any dynamic require that contains a hyphen? I believe I faced the same issue so I would like to check this if it's been deployed and released already @hardfist
