### ISSUE TITLE
Napi Error: GenericFailure - ValidationError: Invalid options object.

### ISSUE THREAD

**Issue by Jdruwe** [web-infra-dev/rspack#3402]
### System Info

  System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 712.31 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Firefox: 113.0.2
    Safari: 16.1

### Details

I am currently getting the following error when running `rspack build -c rspack/rspack.config.js`

```
Napi Error: GenericFailure - ValidationError: Invalid options object. Imports Loader has been initialized using an options object that does not match the API schema.
 - options should be one of these:
   object { imports, … } | object { wrapper, … } | object { additionalCode, … }
   -> Options for imports-loader
   Details:
    * options misses the property 'imports' | should be any non-object.
    * options misses the property 'wrapper' | should be any non-object.
    * options misses the property 'additionalCode' | should be any non-object.
    at validate (/MY-REPO/node_modules/@rspack/core/node_modules/schema-utils/dist/validate.js:115:11)
    at Object.loaderContext.getOptions (/MY-REPO/node_modules/@rspack/core/src/loader-runner/index.ts:513:4)
    at Object.loader (/MY-REPO/node_modules/imports-loader/dist/index.js:23:24)
    at LOADER_EXECUTION (/MY-REPO/node_modules/@rspack/core/src/loader-runner/index.ts:657:14)
    at runSyncOrAsync (/MY-REPO/node_modules/@rspack/core/src/loader-runner/index.ts:658:5)
    at /MY-REPO/node_modules/@rspack/core/src/loader-runner/index.ts:781:3
    at handleResult (/MY-REPO/node_modules/@rspack/core/src/loader-runner/loadLoader.js:76:2)
    at loadLoader (/MY-REPO/node_modules/@rspack/core/src/loader-runner/loadLoader.js:47:10)
    at iterateNormalLoaders (/MY-REPO/node_modules/@rspack/core/src/loader-runner/index.ts:767:2)
    at /MY-REPO/node_modules/@rspack/core/src/loader-runner/index.ts:565:4
    at new Promise (<anonymous>)
    at runLoader (/MY-REPO/node_modules/@rspack/core/src/loader-runner/index.ts:534:9)
    at /MY-REPO/node_modules/@rspack/core/src/compiler.ts:341:31
   0: _napi_register_module_v1
   1: <unknown>
   2: <unknown>
```
I've also tried setting the scss rule to 'type: 'javascript/auto' but got the same result.
Not sure what I am doing wrong, seems like a very generic error to me, any help would be appreciated!

### Reproduce Steps

Rspack config:

```
const { VueLoaderPlugin } = require('vue-loader');
const path = require('path');
const appsPath = path.resolve(__dirname, '../src/main/content/jcr_root/apps/');

/** @type {import('@rspack/cli').Configuration} */
const config = {
    entry: {
        'folder1/dist/index': path.resolve(
            appsPath,
            'folder1/index.ts'
        ),
        'folder2/dist/index': path.resolve(
            appsPath,
            'folder2/index.ts'
        ),
    },
    output: {
        path: appsPath,
    },
    plugins: [new VueLoaderPlugin()],
    module: {
        rules: [
            {
                test: /\.vue$/,
                use: ['vue-loader'],
            },
            {
                resourceQuery: /lang=ts/,
                type: 'ts',
            },
            {
                test: /\.scss$/,
                use: [
                    'vue-style-loader',
                    'css-loader',
                    {
                        loader: 'sass-loader',
                        options: {
                            sassOptions: { quietDeps: true },
                        },
                    },
                ],
                type: 'css',
            },
            {
                test: /\.css/,
                use: ['vue-style-loader', 'css-loader'],
                type: 'javascript/auto',
            },
        ],
    },
    experiments: {
        css: false,
    },
};
module.exports = config;
```

**Comment by h-a-n-a** [comment]
It seems that it's a problem with the option that you passed to `imports-loader`.

**Comment by Jdruwe** [comment]
You are right, sorry, this can be closed!
