### ISSUE TITLE
the package 'schema-utils' should be listed as a dependency for '@rspack/core'.

### ISSUE THREAD

**Issue by hoivee** [web-infra-dev/rspack#3594]
### System Info

System:
    OS: Linux 4.4 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900HX
    Memory: 35.54 GB / 63.74 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm

### Details

Napi Error: GenericFailure - TypeError: validate is not a function
    at Object.loaderContext.getOptions (/mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/index.ts:530:4)
    at Object.lessLoader (/mnt/c/WEB/xxx/node_modules/.pnpm/less-loader@9.1.0_less@3.13.1+webpack@5.75.0/node_modules/less-loader/dist/index.js:19:24)
    at LOADER_EXECUTION (/mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/index.ts:658:14)
    at runSyncOrAsync (/mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/index.ts:659:5)
    at /mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/index.ts:782:3
    at handleResult (/mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/loadLoader.js:76:2)
    at loadLoader (/mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/loadLoader.js:47:10)
    at iterateNormalLoaders (/mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/index.ts:768:2)
    at /mnt/c/WEB/xxx/node_modules/.pnpm/@rspack+core@0.2.3_uaydpeuxkjjcxdbyfgk36cjdxi/node_modules/@rspack/core/src/loader-runner/index.ts:574:4
    at new Promise (<anonymous>)
   0: <unknown>
   1: <unknown>
   2: _ZN6v8impl12_GLOBAL__N_118ThreadSafeFunction7AsyncCbEP10uv_async_s
   3: uv__async_io
             at /home/iojs/build/ws/out/../deps/uv/src/unix/async.c:163:5
   4: uv__io_poll
             at /home/iojs/build/ws/out/../deps/uv/src/unix/epoll.c:374:11
   5: uv_run
             at /home/iojs/build/ws/out/../deps/uv/src/unix/core.c:406:5
   6: _ZN4node13SpinEventLoopEPNS_11EnvironmentE
   7: _ZN4node16NodeMainInstance3RunEv
   8: _ZN4node22LoadSnapshotDataAndRunEPPKNS_12SnapshotDataEPKNS_20InitializationResultE
   9: _ZN4node5StartEiPPc
  10: <unknown>
  11: __libc_start_main
  12: _start

### Reproduce Steps

install @rspack/cli@0.2.3 with pnpm

**Comment by Yinboan** [comment]
I have encountered the same problem, and I believe it was due to my low versions of less and less loader, so upgrading to the latest version seems to have no effect (but I upgraded React from 16.8.6 to 17 to solve the previous problem)
