### ISSUE TITLE
[Tracking issue]webpack test terser-plugin

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#3639]
```[tasklist]
### Tasks
- [ ] compiler.webpack.javascript.JavascriptModulesPlugin.getCompilationHooks(compilation)
```

**Comment by alfaproject** [comment]
I just got this error as well while trying to use the terser plugin:
```
Error: Napi Error: TypeError: Cannot read properties of undefined (reading 'getCompilationHooks')
    at /Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/terser-webpack-plugin/dist/index.js:684:73
    at Hook.eval (eval at create (/Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler._Compiler_compilation (/Users/alfa/Documents/the-mill/lambda-gaming.nosync/node_modules/@rspack/core/dist/Compiler.js:768:28)
```

The reason I'm trying to use the original Terser webpack plugin is because the new SWC one doesn't support the `beautify` option. I've tried to make a prettier plugin but it's a bit slower than I wanted it to be )':

**Comment by chenjiahan** [comment]
terser-webpack-plugin has been supported by https://github.com/web-infra-dev/rspack/pull/6853
