### ISSUE TITLE
[Bug]: missing builtins.html schema check

### ISSUE THREAD

**Issue by krutoo** [web-infra-dev/rspack#3644]
### System Info

System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 268.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.1
  npmPackages:
    @rspack/cli: latest => 0.2.4

### Details

next code:
```js


/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
  context: __dirname,
  entry: './src/index.js',
  output: {
    filename: '[name].js',
  },
  builtins: {
    html: [
      // THIS CAUSES AN ERROR
      ...Object.entries({ a: 1, b: 2 }).map(([key, value]) => ({
        filename: `${key}.html`,
        template: './index.html',
        chunks: key,
      })),
    ],
  },
  module: {
    rules: [
      {
        test: /\.css$/i,
        type: 'css',
      },
      {
        test: /\.module\.css$/i,
        type: 'css/module',
      },
      {
        test: /\.module\.scss$/,
        use: 'sass-loader',
        type: 'css/module',
      },
      {
        test: /\.(apng|avif|gif|jpg|jpeg|png|webp)$/,
        type: 'asset',
      },
    ],
  },
};

```

causes next error:
```sh
> rspack-react-ts-starter@1.0.0 dev
> rspack serve

/Users/user/projects/some-project/node_modules/@rspack/core/dist/compiler.js:549
    __classPrivateFieldSet(this, _Compiler__instance, (_a = __classPrivateFieldGet(this, _Compiler__instance, "f")) !== null && _a !== void 0 ? _a : new binding.Rspack(options, {
                                                                                                                                                     ^

Error: Given napi value is not an array
    at Compiler._Compiler_instance_get (/Users/user/projects/some-project/node_modules/@rspack/core/src/compiler.ts:288:4)
    at __classPrivateFieldGet (/Users/user/projects/some-project/node_modules/@rspack/core/dist/compiler.js:34:48)
    at Compiler.build (/Users/user/projects/some-project/node_modules/@rspack/core/src/compiler.ts:874:24)
    at /Users/user/projects/some-project/node_modules/@rspack/core/src/watching.ts:255:19
    at Hook.eval [as callAsync] (eval at create (/Users/user/projects/some-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/user/projects/some-project/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._Watching_go (/Users/user/projects/some-project/node_modules/@rspack/core/src/watching.ts:238:32)
    at Watching._Watching_invalidate (/Users/user/projects/some-project/node_modules/@rspack/core/src/watching.ts:208:11)
    at /Users/user/projects/some-project/node_modules/@rspack/core/src/watching.ts:62:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'InvalidArg'
```

### Reproduce Steps

1. run `npm i`
2. run `npm run dev`

**Comment by hardfist** [comment]
chunks should be passed as array
```js
[...Object.entries({ a: 1, b: 2 }).map(([key, value]) => ({
		filename: `${key}.html`,
		template: "./index.html",
		chunks: [key] // chunks should be array
	}))]
```

**Comment by hardfist** [comment]
need add zod check for builtins.html to avoid this problem
