### ISSUE TITLE
Is webpack 4 supported in a vue2 project?

### ISSUE THREAD

**Issue by JasonBoy** [web-infra-dev/rspack#3820]
### System Info

System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 130.93 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
    pnpm: 8.3.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.102
    Chrome Canary: 117.0.5900.2
    Edge: 90.0.818.56
    Safari: 16.4
  npmPackages:
    @rspack/cli: ^0.2.8 => 0.2.8

### Details

Try to use it in a vue2-ts project(`@vue/cli-service@4.5`) with `vue-loader@15.10.1`, when build shows errors below(same error when install a webpack to [official vue2-ts example](https://github.com/web-infra-dev/rspack/blob/main/examples/vue2-ts/package.json)):
```
[rspack-cli] [Error: napi error: GenericFailure - TypeError: Cannot read properties of undefined (reading 'tap')
    at /Users/jason/workspace/github/rspack-main/examples/vue2-ts/node_modules/vue-loader/lib/plugin-webpack4.js:15:28
    at Hook.eval (eval at create (/Users/jason/workspace/github/rspack-main/examples/vue2-ts/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
```
It looks like it runs `vue-loader/lib/plugin-webpack4.js` file, but the `normalModuleLoader` is missing(not available in webpack 5 but the project depends on webpack 4):
```js
class VueLoaderPlugin {
  apply(compiler) {
    // add NS marker so that the loader can detect and report missing plugin
    if (compiler.hooks) {
      // webpack 4
      compiler.hooks.compilation.tap(id, (compilation) => {
        console.warn(Object.keys(compilation.hooks))
        const normalModuleLoader = compilation.hooks.normalModuleLoader
        normalModuleLoader.tap(id, (loaderContext) => {
          loaderContext[NS] = true
        })
      })
    }
   // ...
} 

```

### Reproduce link

https://github.com/web-infra-dev/rspack/blob/main/examples/vue2-ts

### Reproduce Steps

1. install webpack 4 `npm i webpack@4 -D`
2. and `npm run build`

**Comment by hardfist** [comment]
rspack doesn't support webpack4-plugin

**Comment by h-a-n-a** [comment]
> > rspack doesn't support webpack4-plugin
> 
> @hardfist ok, so I need to upgrade @vue/cli-service to v5 with other related packages？or is there any other workaround? 😵‍💫

Supporting Webpack4 hooks is not on our radar. You'd better to upgrade to Webpack5 and use the corresponding vue-loader.

**Comment by h-a-n-a** [comment]
I will close this issue but feel free to reopen this if you have any further question. :-)
