### ISSUE TITLE
test:js failed on case `asset-is-dep-of-css-source` 

### ISSUE THREAD

**Issue by suica** [web-infra-dev/rspack#3832]
### System Info
```
  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.08 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /usr/local/bin/node
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.102
    Edge: 114.0.1823.41
    Safari: 16.3
  npmPackages:
    @rspack/cli: workspace:* => 0.2.8
```

### Details

`pnpm run test:js` fails on case `asset-is-dep-of-css-source`.

Related output:
```
│   ● configCases › tree-shaking › asset-is-dep-of-css-source › exported tests › should only import assets that included in chunks
│     expect(received).toBe(expected) // Object.is equality
│     Expected: 1
│     Received: 0
│       11 |     const svgFiles = list.filter((item)=>item.endsWith("svg"));
│       12 |     expect(svgFiles.length).toBe(1);
│     > 13 | });
│          |    ^
│       14 | },
│       15 | "./index.css": function (module, exports, __webpack_require__) {
│       16 | },
│       at tests/configCases/tree-shaking/asset-is-dep-of-css-source/dist/main.js:13:29
│       at Object.fn (tests/helpers/createLazyTestEnv.js:22:15)
│ Test Suites: 1 failed, 1 total
│ Tests:       1 failed, 813 passed, 814 total
│ Snapshots:   14 passed, 14 total
│ Time:        14.286 s
│ Ran all test suites matching /tests\/configCase.test.ts/i.
└─ Failed in 15.3s at /Users/foobar/workspace/rspack/packages/rspack
```

### Reproduce Steps

1. Reset to `37ad034e` (which is the current head of `main`).
2. `pnpm run test:js`

**Comment by suica** [comment]
It seems to be that i ran this command with an old build of rspack-cli.
Build it first and run `test:js` turns to be ok.
```
pnpm run build:cli:debug
```
