### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'refresh')

### ISSUE THREAD

**Issue by my-lalex** [web-infra-dev/rspack#4158]
### System Info

  System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (5) arm64 unknown
    Memory: 14.17 GB / 23.45 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 20.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - /usr/local/bin/npm
    pnpm: 8.6.1 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    @rspack/cli: ^0.3.2 => 0.3.2 
    @rspack/plugin-node-polyfill: ^0.3.2 => 0.3.2 

### Details

My config:
```typescript
import { defineConfig } from '@rspack/cli';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';
import { cwd } from 'node:process';

const NodePolyfill = require('@rspack/plugin-node-polyfill');

module.exports = defineConfig({
	entry: { main: './src/apps/main/web.tsx' },
	context: __dirname,
	mode: 'development',
	module: {
		rules: [
			{
				test: /\.css$/,
				use: [
					{
						loader: 'postcss-loader',
						options: {
							postcssOptions: {
								plugins: {
									'@pandacss/dev/postcss': {},
								},
								// ...
							},
						},
					},
				],
				type: 'css',
			},
		],
	},
	cache: false,
	devServer: {
		hot: false,
		port: 42672,
		historyApiFallback: true,
		devMiddleware: {
			writeToDisk: true,
		},
	},
	output: {
		path: cwd() + '/dist/webapp',
		clean: true,
		publicPath: '/',
	},
	resolve: {
		extensions: ['.js', '.json', '.wasm', '.tsx', '.ts', '.jsx', '.mjs', '.cjs'],
	},
	plugins: [
		//
		new NodePolyfill(),
		new ForkTsCheckerWebpackPlugin(),
	],
	builtins: {
		html: [
			{
				title: '*****,
				template: './resources/index.html',
			},
		],
		progress: true,
	},
});
```
The error thrown
```
TypeError: Cannot read properties of undefined (reading 'refresh')
    at /workspace/node_modules/.pnpm/@rspack+dev-server@0.3.2_@rspack+core@0.3.2_react-refresh@0.14.0/node_modules/@rspack/dev-server/dist/server.js:260:54
    at Array.forEach (<anonymous>)
    at RspackDevServer.initialize (/workspace/node_modules/.pnpm/@rspack+dev-server@0.3.2_@rspack+core@0.3.2_react-refresh@0.14.0/node_modules/@rspack/dev-server/dist/server.js:241:19)
    at RspackDevServer.start (/workspace/node_modules/.pnpm/webpack-dev-server@4.13.1_webpack@5.76.0/node_modules/webpack-dev-server/lib/Server.js:3291:16)
    at async Object.handler (/workspace/node_modules/.pnpm/@rspack+cli@0.3.2_react-refresh@0.14.0_webpack@5.88.2/node_modules/@rspack/cli/dist/commands/serve.js:80:17)
```

### Reproduce Steps

Kinda hard to create a minimalistic project based on the large one I use: the issue seem to come from React refresh (that I don't use or don't want to)

I just can say that it works with v0.3.1

**Comment by clijiac** [comment]
seems this https://www.npmjs.com/package/@rspack/plugin-react-refresh is missing client folder when publish to npm

**Comment by hyf0** [comment]
Fixed by https://github.com/web-infra-dev/rspack/pull/4164. We will release a fixed version tomorrow.

**Comment by pushkargupta9807** [comment]
I am still seeing this issue with the latest rspack v0.3.4 . Is the fix not merged yet ?
Thanks
