### ISSUE TITLE
run nestjs project fail: ReferenceError: self is not defined

### ISSUE THREAD

**Issue by Ttou** [web-infra-dev/rspack#4190]
### System Info

System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 85.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/Library/Caches/fnm_multishells/94004_1694595424477/bin/node
    npm: 8.19.4 - ~/Library/Caches/fnm_multishells/94004_1694595424477/bin/npm
    pnpm: 8.7.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
  npmPackages:
    @rspack/cli: ^0.3.4 => 0.3.4

### Details

```
> rspack serve

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.88.109:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/wangruijin/Projects/issue/rspack-issue-nestjs/public' directory
Rspack ████████████████████████████████████████ 100% done                                                                                                           rspack compiled successfully in 245 ms
/Users/wangruijin/Projects/issue/rspack-issue-nestjs/dist/main.js:13677
RefreshRuntime.injectIntoGlobalHook(self);
                                    ^

ReferenceError: self is not defined
    at Object../node_modules/.pnpm/@rspack+plugin-react-refresh@0.3.4_react-refresh@0.14.0_webpack-dev-server@4.13.1_webpack@5.76.0/node_modules/@rspack/plugin-react-refresh/client/reactRefreshEntry.js (/Users/wangruijin/Projects/issue/rspack-issue-nestjs/dist/main.js:13677:37)
    at __webpack_require__ (/Users/wangruijin/Projects/issue/rspack-issue-nestjs/dist/main.js:60443:33)
    at /Users/wangruijin/Projects/issue/rspack-issue-nestjs/dist/main.js:61366:1
    at Object.<anonymous> (/Users/wangruijin/Projects/issue/rspack-issue-nestjs/dist/main.js:61370:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

### Reproduce link

https://github.com/Ttou/rspack-issue-nestjs

### Reproduce Steps

1. run `npm run dev`
2. terminal report error

**Comment by nanyuantingfeng** [comment]
You can temporarily suppress this error by setting devServer.hot = false and builtins.react.refresh = false.

**Comment by ahabhgk** [comment]
Thanks for reporting, this is fixed, upgrade after next patch release, and add builtins.react.refresh = false
