### ISSUE TITLE
Error with production bundle for `react-virtuoso` (https://virtuoso.dev/)

### ISSUE THREAD

**Issue by hverlin** [web-infra-dev/rspack#4528]
### System Info

```
  System: Linux (ubuntu)
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.9.0 - ~/.asdf/installs/nodejs/18.16.0/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.92
  npmPackages:
    @rspack/cli: latest => 0.3.10
```

### Details

Getting the following error with production bundle for react-virtuoso (https://virtuoso.dev/).
Works in development mode and with webpack
```
main.js:1 Uncaught TypeError: r is not a function
    at main.js:1:250240
    at main.js:1:249849
    at main.js:1:251127
    at main.js:1:250987
    at main.js:1:250601
    at main.js:1:250877
    at x (main.js:1:250224)
    at main.js:1:250750
    at C (main.js:1:250757)
    at main.js:1:263059
```

### Reproduce Steps

Create an app using `rspack`
```shell
pnpm create rspack@latest
pnpm add react-virtuoso
```

Update  `main.jsx` with 

```jsx
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import { Virtuoso } from 'react-virtuoso'

const App = () => (
  <Virtuoso
    style={{ height: '400px' }}
    totalCount={200}
    itemContent={index => <div>Item {index}</div>}
  />
)

ReactDOM.render(<App />, document.getElementById('root'))
```

Updated the `rspack.config.js` to use `production` mode.
```
module.exports = {
	mode: 'production',
	context: __dirname,
	entry: {main: "./src/main.jsx"},
	devServer: {hot: false},
	builtins: {html: [{template: "./index.html"}]},
	module: {rules: [{test: /\.svg$/,type: "asset"}]}
};
```

Run the dev-server
```shell
pnpm run dev 
```

Getting the following error
```
main.js:1 Uncaught TypeError: r is not a function
    at main.js:1:250240
    at main.js:1:249849
    at main.js:1:251127
    at main.js:1:250987
    at main.js:1:250601
    at main.js:1:250877
    at x (main.js:1:250224)
    at main.js:1:250750
    at C (main.js:1:250757)
    at main.js:1:263059
```

**Comment by hverlin** [comment]
I can still reproduce this error.

Reproduction here: https://github.com/hverlin/rspack-repro-virtuoso

**Comment by hverlin** [comment]
it's working now
