### ISSUE TITLE
rspack 4.0 版本编译正常，但运行时 ahooks 下的 exports 未定义

### ISSUE THREAD

**Issue by towavephone** [web-infra-dev/rspack#4771]
### System Info

  System:
    OS: Linux 4.15 Ubuntu 16.04.7 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.44 GB / 15.43 GB
    Container: Yes
    Shell: 5.1.1 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.volta/tools/image/node/16.20.2/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.2/bin/npm
    pnpm: 7.33.6 - ~/.volta/tools/image/pnpm/7.33.6/bin/pnpm
  Browsers:
    Chrome: 111.0.5563.64
  npmPackages:
    @rspack/cli: 0.4.0 => 0.4.0 
    @rspack/core: 0.4.0 => 0.4.0 

### Details

rspack 编译正常，但在运行时候网页白屏，报以下错误
```bash
Uncaught ReferenceError: exports is not defined
    at ./node_modules/.pnpm/ahooks@3.3.10_react@18.2.0/node_modules/ahooks/lib/useRequest/src/Fetch.js (Fetch.js:210:23)
    at __webpack_require__ (three.module.js:50683:7956)
    at fn (three.module.js:50683:7956)
    at ./node_modules/.pnpm/ahooks@3.3.10_react@18.2.0/node_modules/ahooks/lib/useRequest/src/useRequestImplement.js (useRequestImplement.js:89:31)
    at __webpack_require__ (three.module.js:50683:7956)
    at fn (three.module.js:50683:7956)
    at ./node_modules/.pnpm/ahooks@3.3.10_react@18.2.0/node_modules/ahooks/lib/useRequest/src/useRequest.js (useRequest.js:64:45)
    at __webpack_require__ (three.module.js:50683:7956)
    at fn (three.module.js:50683:7956)
    at ./node_modules/.pnpm/ahooks@3.3.10_react@18.2.0/node_modules/ahooks/lib/useRequest/index.js (index.js:14:36)
```

把默认转换开启后编译，运行正常
```js
experiments: {
    rspackFuture: {
      disableTransformByDefault: false, // 开启默认转换
    }
  }
```

完整配置如下：
```js
const path = require('path')
const { defineConfig } = require('@rspack/cli')
const fs = require('fs')
const rspack = require('@rspack/core')
// const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin')
// const NodePolyfill = require('@rspack/plugin-node-polyfill')

const appDirectory = fs.realpathSync(process.cwd())
const resolveApp = relativePath => path.resolve(appDirectory, relativePath)

const dotenv = resolveApp('.env')

const NODE_ENV = process.env.NODE_ENV
// https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use
const dotenvFiles = [
  `${dotenv}.${NODE_ENV}.local`,
  // Don't include `.env.local` for `test` environment
  // since normally you expect tests to produce the same
  // results for everyone
  NODE_ENV !== 'test' && `${dotenv}.local`,
  `${dotenv}.${NODE_ENV}`,
  dotenv
].filter(Boolean)

// Load environment variables from .env* files. Suppress warnings using silent
// if this file is missing. dotenv will never modify any environment variables
// that have already been set.  Variable expansion is supported in .env files.
// https://github.com/motdotla/dotenv
// https://github.com/motdotla/dotenv-expand
dotenvFiles.forEach(dotenvFile => {
  if (fs.existsSync(dotenvFile)) {
    require('dotenv-expand')(
      require('dotenv').config({
        path: dotenvFile
      })
    )
  }
})

const { DISABLE_OVERLAY } = process.env

module.exports = defineConfig({
  mode: 'development',
  entry: {
    main: './src/index.js'
  },
  builtins: {
    // html: [
    //   {
    //     template: './public/index.html'
    //   }
    // ],
    // pluginImport: [
    //   {
    //     libraryName: 'antd',
    //     libraryDirectory: 'es',
    //     style: true
    //   }
    // ]
    // define: {
    //   // 'process.env.NODE_ENV': "'development'",
    //   'import.meta.env': "'development'",
    //   'import.meta.env.MODE': "'development'",
    //   'process.env.NODE_DEBUG': false,
    //   'process.env.BUILD_TOOL': "'rspack'"
    // }
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: /src/,
        use: {
          loader: 'builtin:swc-loader',
          options: {
            // Enable source map
            sourceMap: true,
            jsc: {
              parser: {
                syntax: 'ecmascript',
                jsx: true
              },
              externalHelpers: true,
              preserveAllComments: false,
              transform: {
                react: {
                  runtime: 'automatic',
                  pragma: 'React.createElement',
                  pragmaFrag: 'React.Fragment',
                  throwIfNamespace: true,
                  useBuiltins: false
                }
              }
            },
            rspackExperiments: {
              import: [
                {
                  libraryName: 'antd',
                  libraryDirectory: 'es',
                  style: true
                }
              ]
            }
          }
        },
        type: 'javascript/auto',
        // type: 'jsx'
      },
      {
        test: /\.less$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'less-loader',
            options: {
              lessOptions: { javascriptEnabled: true }
            }
          }
        ],
        type: 'css/module'
      },
      {
        test: /\.less$/,
        include: /node_modules/,
        use: [
          {
            loader: 'less-loader',
            options: {
              lessOptions: { javascriptEnabled: true }
            }
          }
        ],
        type: 'css'
      },
      // {
      //   test: /\.css$/,
      //   type: 'css'
      // },
      {
        test: /\.(png|svg|jpg|jpeg|ttf)$/,
        type: 'asset'
      }
    ]
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      'antd/es/theme': false // 修复因 @ant-design/pro-components 导致的编译报错问题
    },
    extensions: ['.js'],
    mainFields: ['main', 'browser', 'module']
  },
  // plugins: [
  //   new MonacoWebpackPlugin({
  //     languages: ['json']
  //   })
  //   // new NodePolyfill()
  // ],
  devServer: {
    port: 3000,
    allowedHosts: 'all',
    client: {
      overlay: !DISABLE_OVERLAY
    }
  },
  devtool: 'source-map',
  snapshot: {
    resolve: {
      hash: true,
      timestamp: false
    },
    module: {
      hash: true,
      timestamp: false
    }
  },
  experiments: {
    rspackFuture: {
      // 先开启默认转换，因为有些三方库不兼容，比如会报 ahooks 下的 export 未定义
      // disableTransformByDefault: false, // 开启默认转换
      newResolver: false
    }
  },
  stats: {
    preset: 'errors-only',
    reasons: true,
    hash: true,
    builtAt: true,
    timings: true
  },
  plugins: [
    new rspack.HtmlRspackPlugin({
      template: './public/index.html'
    }),
    new rspack.ProgressPlugin(),
    new rspack.DefinePlugin({
      // 'process.env.NODE_ENV': "'development'",
      'import.meta.env': "'development'",
      'import.meta.env.MODE': "'development'",
      'process.env.NODE_DEBUG': false,
      'process.env.BUILD_TOOL': "'rspack'"
    })
  ]
})
```

### Reproduce Steps

1. pnpm i ahooks@3.3.10
2. 复制以上的配置
3. 启动项目

**Comment by hardfist** [comment]
@towavephone it seems fixed in 0.4.1, can you give it a try
