### ISSUE TITLE
should pass webpack-test/cases/parsing/issue-7519/test.config.js with new tree shaking enable

### ISSUE THREAD

**Issue by IWANABETHATGUY** [web-infra-dev/rspack#4834]
### System Info

not related

### Details

```js
 FAIL  ./TestCasesNormal.basictest.js (101 MB heap size)
  ● TestCases › normal › parsing › issue-7519 › exported tests › mult should not be used

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      55 |         (0, _a__WEBPACK_IMPORTED_MODULE_0__.mult)(2);
      56 |     }
    > 57 |     expect(_a__WEBPACK_IMPORTED_MODULE_0__.multUsed).toBe(false);
         |                                                      ^
      58 | });
      59 | }),
      60 |

      at js/normal/parsing/issue-7519/bundle.js:57:54
      at Object.rfn (helpers/createLazyTestEnv.js:23:15)

```
should be unused, but we don't shake it.

### Reproduce link

current repo

### Reproduce Steps

cd webpack-test
pnpm test

**Comment by IWANABETHATGUY** [comment]
wired thing is it woked when I extracted this as a single project, 
use this config: 
```js
const rspack = require("@rspack/core");
/** @type {import('@rspack/cli').Configuration} */
const config = {
	entry: "./src/index.js",
	mode: 'development',
	optimization: {
		usedExports: true,
		sideEffects: true,
		providedExports: true,
		innerGraph: true
	},
	plugins: [
		new rspack.HtmlRspackPlugin({
			template: "./index.html"
		})
	],
	experiments: {
		rspackFuture: {
			newTreeshaking: true
		}
	},

};
module.exports = config;

```
## Output


```js
(function() {
var __webpack_modules__ = {
"./src/a.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.r(__webpack_exports__);
__webpack_require__.d(__webpack_exports__, {
  count: function() { return count; },
  inc: function() { return inc; },
  incTruthy: function() { return incTruthy; },
  setCount: function() { return setCount; },
  multUsed: function() { return multUsed; }
});
 let count = 1;
 function inc() {
    count++;
}
 function incTruthy() {
    count++;
    return true;
}
 function mult(n) {
    count *= n;
}
 function setCount(c) {
    count = c;
}
 const multUsed = false;
}),
"./src/index.js": (function (__unused_webpack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */var _a__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./a */"./src/a.js");

it("logical 'and' should work", ()=>{
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.setCount)(1);
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)();
    expect(_a__WEBPACK_IMPORTED_MODULE_0__.count).toBe(2);
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)();
    expect(_a__WEBPACK_IMPORTED_MODULE_0__.count).toBe(3);
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)() && (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)();
    /* inc itself returns undefined */ expect(_a__WEBPACK_IMPORTED_MODULE_0__.count).toBe(4);
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.incTruthy)() && (0, _a__WEBPACK_IMPORTED_MODULE_0__.incTruthy)();
    expect(_a__WEBPACK_IMPORTED_MODULE_0__.count).toBe(6);
});
it("logical 'or' should work", ()=>{
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.setCount)(1);
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)();
    expect(_a__WEBPACK_IMPORTED_MODULE_0__.count).toBe(2);
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)() || (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)();
    expect(_a__WEBPACK_IMPORTED_MODULE_0__.count).toBe(4);
});
it("mult should not be used", ()=>{
    (0, _a__WEBPACK_IMPORTED_MODULE_0__.inc)();
    expect(_a__WEBPACK_IMPORTED_MODULE_0__.multUsed).toBe(false);
});
}),

}

```
