### ISSUE TITLE
Failed to parse request query with JSON format including # sign

### ISSUE THREAD

**Issue by Asuka109** [web-infra-dev/rspack#4838]
### System Info

```
  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 61.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/Library/Caches/fnm_multishells/91112_1701354169556/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/91112_1701354169556/bin/npm
  Browsers:
    Edge: 119.0.2151.97
    Safari: 17.0
  npmPackages:
    @rspack/cli: workspace:* => 0.4.1
```

### Details

Loader can't get correct options from request just like `/vanilla-extract-css/node_modules/@vanilla-extract/webpack-plugin/virtualFileLoader/dist/vanilla-extract-webpack-plugin-virtualFileLoader.cjs.js?{"fileName":"src/sprinkles.css.ts.vanilla.css","source":"#H4sIAAAAAAAAE62cSZPiSB..."}!/@vanilla-extract/webpack-plugin/extracted.js`.

```js
export default function loader() {
  const opts = this.getOptions();
  //         ^? { ["{\"fileName\":\"src/sprinkles.css.ts.vanilla.css\",\"source\":\""]: "" }
}
```

It seems an issue about:

https://github.com/web-infra-dev/rspack/blob/4c9efbe056434d840d7c9ad7c684faa010c58db0/packages/rspack/src/loader-runner/index.ts#L44-L55

Expect:

```json
{
  "fragment": "",
  "path": "/vanilla-extract-css/node_modules/@vanilla-extract/webpack-plugin/virtualFileLoader/dist/vanilla-extract-webpack-plugin-virtualFileLoader.cjs.js",
  "query": "?{\"fileName\":\"src/sprinkles.css.ts.vanilla.css\",\"source\":\"#H4sIAAAAAAAAE62cSZPiSB...\"}"
}
```

Actual:

```json
{
  "fragment": "#H4sIAAAAAAAAE62cSZPiSB...\"}!/@vanilla-extract/webpack-plugin/extracted.js",
  "path": "/vanilla-extract-css/node_modules/@vanilla-extract/webpack-plugin/virtualFileLoader/dist/vanilla-extract-webpack-plugin-virtualFileLoader.cjs.js",
  "query": "?{\"fileName\":\"src/sprinkles.css.ts.vanilla.css\",\"source\":\""
}
```

That will breaking the webpack plugin of vanilla extract css:

https://github.com/vanilla-extract-css/vanilla-extract/blob/27552826716993d9923d2aa5f30513594ff3c1ee/packages/webpack-plugin/src/loader.ts#L107-L112

I will try to fix this issue and match the behaviour of webpack.

### Reproduce Steps

As above.

**Comment by Asuka109** [comment]
I have created a reproduction case and found that rspack parses the resource of an inline loader with `parsePathQueryFragment`, which is inherited from loader-runner. This will cause a break if the resource includes a # symbol:

```
Error: 
    at eval (eval-a6646d0a.repl:1:1)
    at parsePathQueryFragment (/Users/asuka109/repositories/rspack/packages/rspack/src/loader-runner/index.ts:50:2)
    at parsePathQueryFragment (/Users/asuka109/repositories/rspack/packages/rspack/src/loader-runner/index.ts:169:27)
    at Array.map (<anonymous>)
    at map (/Users/asuka109/repositories/rspack/packages/rspack/src/loader-runner/index.ts:168:54)
```

However, for webpack@5, it uses `parseResourceWithoutFragment` and copes well with the # symbol.

```
Error: 
    at eval (eval-8c5b9c07.repl:1:1)
    at _parseResourceWithoutFragment (/Users/asuka109/repositories/rspack/node_modules/webpack/lib/util/identifier.js:340:2)
    at /Users/asuka109/repositories/rspack/node_modules/webpack/lib/util/identifier.js:121:19
    at /Users/asuka109/repositories/rspack/node_modules/webpack/lib/NormalModuleFactory.js:420:32
    at Array.map (<anonymous>)
    at /Users/asuka109/repositories/rspack/node_modules/webpack/lib/NormalModuleFactory.js:419:30
    at Hook.eval [as callAsync] (eval at create (/Users/asuka109/repositories/rspack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at /Users/asuka109/repositories/rspack/node_modules/webpack/lib/NormalModuleFactory.js:274:24
    at _next0 (eval at create (/Users/asuka109/repositories/rspack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/Users/asuka109/repositories/rspack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at next (/Users/asuka109/repositories/rspack/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:146:43)
    at handleExternals (/Users/asuka109/repositories/rspack/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:152:7)
    at /Users/asuka109/repositories/rspack/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:249:5
    at Hook.eval [as callAsync] (eval at create (/Users/asuka109/repositories/rspack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at /Users/asuka109/repositories/rspack/node_modules/webpack/lib/NormalModuleFactory.js:815:25
    at Hook.eval [as callAsync] (eval at create (/Users/asuka109/repositories/rspack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at NormalModuleFactory.create (/Users/asuka109/repositories/rspack/node_modules/webpack/lib/NormalModuleFactory.js:787:28)
    at Compilation._factorizeModule (/Users/asuka109/repositories/rspack/node_modules/webpack/lib/Compilation.js:1979:11)
    at /Users/asuka109/repositories/rspack/node_modules/webpack/lib/util/AsyncQueue.js:305:10
    at Hook.eval [as callAsync] (eval at create (/Users/asuka109/repositories/rspack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/Users/asuka109/repositories/rspack/node_modules/webpack/lib/util/AsyncQueue.js:295:26)
    at AsyncQueue._ensureProcessing (/Users/asuka109/repositories/rspack/node_modules/webpack/lib/util/AsyncQueue.js:282:12)
    at processImmediate (node:internal/timers:466:21)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

Seems we need to refactor the whole loader-runner?
