### ISSUE TITLE
Error: Missing field `options`

### ISSUE THREAD

**Issue by f0reclone** [web-infra-dev/rspack#4958]
### System Info

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 57.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    pnpm: 8.6.5 - ~/.nvm/versions/node/v18.13.0/bin/pnpm
  Browsers:
    Brave Browser: 106.1.44.101
    Chrome: 120.0.6099.71
    Edge: 120.0.2210.61
    Safari: 16.4
  npmPackages:
    @rspack/cli: 0.4.1 => 0.4.1
    @rspack/core: 0.4.1 => 0.4.1

### Details

```
Error: Missing field `options`
    at Compiler._Compiler_getInstance (/Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/@rspack/cli/node_modules/@rspack/core/dist/Compiler.js:516:55)
    at Compiler.build (/Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/@rspack/cli/node_modules/@rspack/core/dist/Compiler.js:380:87)
    at /Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/@rspack/cli/node_modules/@rspack/core/dist/Watching.js:269:27
    at Hook.eval [as callAsync] (eval at create (/Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._Watching_go (/Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/@rspack/cli/node_modules/@rspack/core/dist/Watching.js:253:34)
    at Watching._Watching_invalidate (/Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/@rspack/cli/node_modules/@rspack/core/dist/Watching.js:217:74)
    at /Users/andreas.neufeld/Code/aboutyou-panel-application/node_modules/@rspack/cli/node_modules/@rspack/core/dist/Watching.js:51:94
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'InvalidArg'
}
```

For some reason it works only again if the node_modules folder is deleted and then reverted to 0.4.0. Using bun 1.0.15 as a package manager.

### Reproduce Steps

1. Upgrade from 0.3.14 to 0.4.x
2. npx rspack serve
3. Error is shown

**Comment by lovetingyuan** [comment]
same issue +1

**Comment by hardfist** [comment]
check whether @rspack/binding and @rspack/core are same version in your node_modules

**Comment by lovetingyuan** [comment]
> check whether @rspack/binding and @rspack/core are same version in your node_modules

--node_modules
--playground
      --node_modules
      --rspack-project

the first node_modules contains @rspack/core and binding, both version is 0.4.2
the inner node_modules(beside rspack-project) also contains @rspack/core and binding, both version is 0.4.0
I delete the inner node_modules/@rspack/core(binding), rspack works well.

I am not sure why there are two node_modules. (I am using npm workspace).
```json
"workspaces": [
    ".",
    "playground/*"
  ],
```

**Comment by hardfist** [comment]
seems your issue is resolved

**Comment by lovetingyuan** [comment]
> seems your issue is resolved

What? I had to manually delete the problem to get rid of it, at least I think rspack's case support for monorepo is problematic.

**Comment by f0reclone** [comment]
I think this is related to bun.

**Steps to reproduce:**
1. Install bun: 
`curl -fsSL https://bun.sh/install | bash`
2. clone rspack repro
`git clone git@github.com:web-infra-dev/rspack-repro.git`
3. `cd rspack-dist`

5. Run `bun run dev:rspack`


**Working example:**
1. Install pnpm
2. clone rspack repro
3. cd rspack-dist
4. Run pnpm run dev:rspack

**Comment by hardfist** [comment]
@f0reclone  I can't reproduce following your step, you can commit the node_modules so we can investigate

**Comment by hardfist** [comment]
@lovetingyuan  please provide repro
