### ISSUE TITLE
InvalidateConfigurationError:

### ISSUE THREAD

**Issue by luoriwusheng-xia** [web-infra-dev/rspack#5438]
### System Info

```
node: 20.10.0
window: 10
```

### Details

```js
const path = require('path')
const rspack = require("@rspack/core");
const { VueLoaderPlugin } = require("vue-loader");

/**
 * @type {import('@rspack/cli').Configuration}
 */
module.exports = {
  context: __dirname,
  entry: {
    main: "./src/main.js"
  },
  devServer: {
		historyApiFallback: true
	},
  plugins: [
		new VueLoaderPlugin(),
		new rspack.HtmlRspackPlugin({
			template: "./public/index.html"
		})
	],

  resolve: {
    alias: {
      "@": path.resolve(__dirname, 'src')
    }
  },
  module: {
    rules: [

      {
        test: /\.vue$/,
        use: [
          {
            loader: "vue-loader",
            options: {
              experimentalInlineMatchResource: true
            }
          }
        ]
      },
      {
        test: /\.less$/,
        loader: "less-loader",
        type: "css"
      },
      {
        test: /\.scss$/,
        loader: "sass-loader",
        type: "css"
      },
      {
        test: /\.svg$/,
        type: "asset/resource"
      },
    ]
  }
};

```

package.json

```json
{
  "name": "vue-element-admin",
  "version": "4.4.0",
  "description": "A magical vue admin. An out-of-box UI solution for enterprise applications. Newest development stack of vue. Lots of awesome features",
  "author": "Pan <panfree23@gmail.com>",
  "scripts": {
    "dev": "rspack serve",
    "build": "rspack build",
    "lint": "eslint --ext .js,.vue src",
    "build:prod": "vue-cli-service build",
    "build:stage": "vue-cli-service build --mode staging",
    "preview": "node build/index.js --preview",
    "new": "plop",
    "svgo": "svgo -f src/icons/svg --config=src/icons/svgo.yml",
    "test:unit": "jest --clearCache && vue-cli-service test:unit",
    "test:ci": "npm run lint && npm run test:unit"
  },
  "dependencies": {
    "axios": "0.18.1",
    "clipboard": "2.0.4",
    "codemirror": "5.45.0",
    "core-js": "3.6.5",
    "driver.js": "0.9.5",
    "dropzone": "5.5.1",
    "echarts": "4.2.1",
    "element-ui": "2.13.2",
    "file-saver": "2.0.1",
    "fuse.js": "3.4.4",
    "js-cookie": "2.2.0",
    "jsonlint": "1.6.3",
    "jszip": "3.2.1",
    "normalize.css": "7.0.0",
    "nprogress": "0.2.0",
    "path-to-regexp": "2.4.0",
    "screenfull": "4.2.0",
    "script-loader": "0.7.2",
    "sortablejs": "1.8.4",
    "vue": "^2.7.16",
    "vue-count-to": "1.0.13",
    "vue-router": "3.0.2",
    "vue-splitpane": "1.0.4",
    "vuedraggable": "2.20.0",
    "vuex": "3.1.0",
    "xlsx": "0.14.1"
  },
  "devDependencies": {
    "@rspack/cli": "^0.1.0",
    "@rspack/core": "^0.5.2",
    "css-loader": "^6.9.1",
    "less": "^4.2.0",
    "less-loader": "^12.1.0",
    "vue-loader": "^15.11.1",
    "vue-style-loader": "^4.1.3"
  },
  "bugs": {
    "url": "https://github.com/PanJiaChen/vue-element-admin/issues"
  },
  "keywords": [
    "vue",
    "admin",
    "dashboard",
    "element-ui",
    "boilerplate",
    "admin-template",
    "management-system"
  ],
  "license": "MIT",
  "lint-staged": {
    "src/**/*.{js,vue}": [
      "eslint --fix",
      "git add"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/PanJiaChen/vue-element-admin.git"
  }
}

```

目前项目无法启动。提示配置错误， 但是具体哪里有问题，还有点懵

错误信息
```
InvalidateConfigurationError:
  /module/rules/1: must pass "enum" keyword validation
  /module/rules/1: must NOT have additional properties
  /module/rules/1: must match a schema in anyOf
  /module/rules: must match exactly one schema in oneOf
    at rspack (D:\参考资料\vue-element-admin\node_modules\@rspack\cli\node_modules\@rspack\core\src\rspack.ts:104:9)
    at RspackCLI.createCompiler (D:\参考资料\vue-element-admin\node_modules\@rspack\cli\src\rspack-cli.ts:46:26)
    at Object.handler (D:\参考资料\vue-element-admin\node_modules\@rspack\cli\src\commands\serve.ts:19:22)
```

### Reproduce Steps

1. clone  vue-element-admin 代码仓库， 尝试做一下改造
2. 删除了原始仓库的 dev 依赖
3. 重新安装 rspack相关依赖 + 配置文件
4. rspack dev

**Comment by luoriwusheng-xia** [comment]
这个 原始项目我就删除了  富文本的包，跟组件， 高版本的node跟富文本的有冲突。 别的 src下面的 未动代码

**Comment by luoriwusheng-xia** [comment]
没事了， 不知道为啥，我下载的 @rspack/cli  是  0.1.0, 正常情况应该是 `0.5.2`, 我的问题
