### ISSUE TITLE
[Bug]: syntax error occurs when use `eval-cheap-module-source-map`

### ISSUE THREAD

**Issue by Clarkkkk** [web-infra-dev/rspack#5757]
### System Info

  System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800 8-Core Processor
    Memory: 11.92 GB / 31.87 GB
  Browsers:
    Edge: Chromium (121.0.2277.128), ChromiumDev (123.0.2400.1)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rsbuild/core: ^0.4.4 => 0.4.4

### Details

Syntax error occurs in the production build when using `eval-cheap-module-source-map` in `output.sourceMap.js`

```
Uncaught SyntaxError: Unexpected token '>'
    at 596 (index.2d522a2e.js:1:59)
    at __webpack_require__ (index.2d522a2e.js:1:38681)
    at eval (eval at 224 (index.2d522a2e.js:1:36210), <anonymous>:5:67)
    at 224 (index.2d522a2e.js:1:36210)
    at __webpack_require__ (index.2d522a2e.js:1:38681)
    at index.2d522a2e.js:1:40883
    at __webpack_require__.O (index.2d522a2e.js:1:39399)
    at index.2d522a2e.js:1:40952
    at index.2d522a2e.js:1:40976
```

I have this error in an rsbuild project, but i believe it is an rspack issue, because the config below also causes the same error:
```js
export default defineConfig({
  plugins: [pluginVue2()],
  tools: {
    rspack: {
      devtool: 'eval-cheap-module-source-map'
    },
  },
  output: {
    sourceMap: {
      js: false,
      css: false
    }
  }
});
```

### Reproduce link

https://github.com/Clarkkkk/rsbuild-issue

### Reproduce Steps

```sh
pnpm install
npm run build
npm run preview
```

**Comment by xc2** [comment]
Reproducible when 
- `devtool` includes `eval`
- `minimize` is on
- `/-->/` in source code

## What's wrong

1. All `/-->/` texts - not only code - become `--\x3e` while `/--\x3e/` expected.
2. Only `/-->/` has been found to have this problem.

## Minimal repro

### `src/index.js`
```js
// 1
console.log(/-->/);
// 2
console.log("/-->/");
// 3
// /-->/
```

### `rspack.config.js`

```js
module.exports = /** @type {import('@rspack/core').Configuration} */ ({
  mode: "none",
  devtool: "eval",
  entry: "./src/index.js",
  optimization: {
    minimize: true,
  },
});
```

### [rspack] output

```js
!function(){var __webpack_modules__={"./src/index.js":function(){eval('// 1\nconsole.log(--\x3e);\n// 2\nconsole.log("--\x3e"); // 3\n // --\x3e\n\n//# sourceURL=webpack:///./src/index.js?')}},__webpack_module_cache__={};function __webpack_require__(n){var r=__webpack_module_cache__[n];if(void 0!==r)return r.exports;var o=__webpack_module_cache__[n]={exports:{}};return __webpack_modules__[n](o,o.exports,__webpack_require__),o.exports}var __webpack_exports__=__webpack_require__("./src/index.js")}();
```

### [webpack] output

```js
(()=>{var __webpack_modules__=[()=>{eval('// 1\nconsole.log(/--\x3e/);\n// 2\nconsole.log("/--\x3e/");\n// 3\n// /--\x3e/\n\n\n//# sourceURL=webpack:///./src/index.js?')}],__webpack_exports__={};__webpack_modules__[0]()})();
```

### [rspack] When `minimize` is `false`

```js
(function() {
var __webpack_modules__ = {
"./src/index.js": (function () {
eval("// 1\nconsole.log(/-->/);\n// 2\nconsole.log(\"/-->/\"); // 3\n // /-->/\n\n//# sourceURL=webpack:///./src/index.js?");}),

}
// The module cache
 var __webpack_module_cache__ = {};
function __webpack_require__(moduleId) {
// Check if module is in cache
        var cachedModule = __webpack_module_cache__[moduleId];
        if (cachedModule !== undefined) {
      return cachedModule.exports;
      }
      // Create a new module (and put it into the cache)
      var module = (__webpack_module_cache__[moduleId] = {
       exports: {}
      });
      // Execute the module function
      __webpack_modules__[moduleId](module, module.exports, __webpack_require__);
// Return the exports of the module
 return module.exports;

}
var __webpack_exports__ = __webpack_require__("./src/index.js");
})()
```

**Comment by xc2** [comment]
## a smaller repro without `devtool` and `eval`

### `rspack.config.js`

```js
module.exports = /** @type {import('@rspack/core').Configuration} */ ({
  mode: "none",
  devtool: false,
  entry: "./src/index.js",
  optimization: {
    minimize: true,
  },
});
```

### `src/index.js`

```js
foo("/-->/");
```

### [rspack] output

```js
(function(){var r={"./src/index.js":function(){foo("--\x3e")}},n={};!function o(t){var e=n[t];if(void 0!==e)return e.exports;var s=n[t]={exports:{}};return r[t](s,s.exports,o),s.exports}("./src/index.js")})();
```

**Comment by ahabhgk** [comment]
So is this a minimize bug? @xc2

**Comment by xc2** [comment]
> Thanks for your investigate, so is this a minimize bug? @xc2

seems yes.

btw,  i tried compress `foo("/-->/");` with [swc_ecma_minifier's example](https://github.com/swc-project/swc/blob/main/crates/swc_ecma_minifier/examples/minifier.rs) and it gave `foo("/-->/");` as result

**Comment by xc2** [comment]
@Clarkkkk workaround:

```ts
// rsbuild.config.ts


export default defineConfig({
// ...
  tools: {
    bundlerChain: (chain, { CHAIN_ID }) => {
      chain.optimization
        .minimizer(CHAIN_ID.MINIMIZER.JS)
        .merge({ args: [{ format: { inlineScript: false } }] });
    }
  },
});
```

**Comment by Clarkkkk** [comment]
Thank! I will try it.

**Comment by xc2** [comment]
fix will be shipped within
- swc: 1.4.3
- rspack: unknown
- rsbuild: unknown

for those who're suffering from the issue with package vkbeautify, please try disabling `format.inlineScript` of [SwcJsMinimizerRspackPlugin](https://www.rspack.dev/config/plugins.html#swcjsminimizerrspackplugin).
