### ISSUE TITLE
[Bug]: failed to retrieve chunk name

### ISSUE THREAD

**Issue by theninthsky** [web-infra-dev/rspack#6078]
### System Info

Operating System: Windows 11
Node Version: 20.11.1
Rspack CLI Version: 0.5.9

### Details

```
Panic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  failed to retrieve chunk name:   × TypeError: Cannot read properties of undefined (reading 'map')
  │     at name (C:\Projects\client-side-rendering\rspack.config.js:77:45)
  │     at C:\Projects\client-side-rendering\node_modules\@rspack\core\dist\builtin-plugin\SplitChunksPlugin.js:37:28
  │

Location: crates\rspack_binding_options\src\options\raw_split_chunks\raw_split_chunk_name.rs:42

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: napi_register_module_v1
    at <unknown source file>
 2: napi_register_module_v1
    at <unknown source file>
 3: napi_register_module_v1
    at <unknown source file>
 4: napi_register_module_v1
    at <unknown source file>
 5: napi_register_module_v1
    at <unknown source file>
 6: wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 8: napi_register_module_v1
    at <unknown source file>
 9: napi_register_module_v1
    at <unknown source file>
10: napi_register_module_v1
    at <unknown source file>
11: napi_register_module_v1
    at <unknown source file>
12: napi_register_module_v1
    at <unknown source file>
13: napi_register_module_v1
    at <unknown source file>
14: napi_register_module_v1
    at <unknown source file>
15: napi_register_module_v1
    at <unknown source file>
16: napi_register_module_v1
    at <unknown source file>
17: napi_register_module_v1
    at <unknown source file>
18: napi_register_module_v1
    at <unknown source file>
19: napi_register_module_v1
    at <unknown source file>
20: napi_register_module_v1
    at <unknown source file>
21: napi_register_module_v1
    at <unknown source file>
22: napi_register_module_v1
    at <unknown source file>
23: wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
24: napi_register_module_v1
    at <unknown source file>
25: napi_register_module_v1
    at <unknown source file>
26: napi_register_module_v1
    at <unknown source file>
27: napi_register_module_v1
    at <unknown source file>
28: BaseThreadInitThunk
    at <unknown source file>
29: RtlUserThreadStart
    at <unknown source file>
```

### Reproduce Steps

Create the following optimization in a project (coming from Webpack):

```
 optimization: {
      runtimeChunk: 'single',
      splitChunks: {
        chunks: 'initial',
        cacheGroups: {
          vendors: {
            test: /[\\/]node_modules[\\/]/,
            chunks: 'all',
            minSize: 100000,
            name: (module, chunks) => {
              const allChunksNames = chunks.map(({ name }) => name).join('.')
              const moduleName = (module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/) || [])[1]

              return `${moduleName}.${allChunksNames}`.replace('@', '')
            }
          }
        }
      }
    },
```

The purpose of this splitChunks configuration is to extract dependencies from async chunks and combine them.
A thorough explanation can be found here:
https://github.com/theninthsky/client-side-rendering?tab=readme-ov-file#preventing-duplicate-async-vendors

**Comment by h-a-n-a** [comment]
Rspack does not support `chunks` as the second argument.

**Comment by theninthsky** [comment]
Thanks.

**Comment by theninthsky** [comment]
@h-a-n-a 
Is there a plan to support this feature?
Especially since it's not a plugin, but rather a core Webpack property.

**Comment by h-a-n-a** [comment]
> @h-a-n-a 
> 
> Is there a plan to support this feature?
> 
> Especially since it's not a plugin, but rather a core Webpack property.

@theninthsky Yes, we can support this and PR is welcome.

**Comment by mxmason** [comment]
Hi, @h-a-n-a. I'm also very interested in this fix, as it blocks me from migrating to RSpack. 

My team has a django app that relies on a manifest file to look up build chunks when rendering html files. This same bug prevents the chunks from being mapped into the manifest file.
