### ISSUE TITLE
[Bug]: issue with `require` and `mui/x-tree-view` in production bundle

### ISSUE THREAD

**Issue by hverlin** [web-infra-dev/rspack#6129]
### Version

```sh
npmPackages:
    @rsbuild/core: ^0.5.7 => 0.5.7
    @rsbuild/plugin-react: ^0.5.7 => 0.5.7
```

### Details
We have an internal library which re-export some components from `@mui/x-tree-view` in CJS
![image](https://github.com/web-infra-dev/rsbuild/assets/9151470/482bf404-73a2-4de9-831d-1c8c60a771a8)

When moving from `webpack` to  `rsbuild`, we have found an issue when importing this component with the production bundle only.

```
lib-react.aeffa8f6.js:2 Error: Minified React error web-infra-dev/rsbuild#130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oG (lib-react.aeffa8f6.js:2:121039)
    at o (lib-react.aeffa8f6.js:2:57547)
```
which translates to 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.[missing argument]
```

I have created a minimal reproducer here: https://github.com/hverlin/rsbuild-mui-tree-view/

```tsx
// does not work with production build
const _xTreeView = require('@mui/x-tree-view');
const { TreeView, TreeItem } = _xTreeView;

// works
// import {TreeView, TreeItem} from '@mui/x-tree-view';

export function FirstComponent() {
    return (
        <TreeView>
            <TreeItem nodeId="1" label="Applications" />
        </TreeView>
    );
}
```

Is this behavior expected? It seems that if it's supported in development build and by webpack, it should also works with the production build?

### Reproduce link

https://github.com/hverlin/rsbuild-mui-tree-view/

### Reproduce Steps

```shell
git clone https://github.com/hverlin/rsbuild-mui-tree-view.git
pnpm i
NODE_ENV=production pnpm dev
```

You can then update https://github.com/hverlin/rsbuild-mui-tree-view/blob/master/src/App.tsx
and change the import to see that it works.

**Comment by chenjiahan** [comment]
It seems like a bug of Rspack

**Comment by IWANABETHATGUY** [comment]
The old tree shaking impl has some interop issues, please change to new `treeShaking` impl
```js
import { defineConfig } from '@rsbuild/core';
import { pluginReact } from '@rsbuild/plugin-react';

export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    rspack: {
      experiments: {
        rspackFuture: {
          newTreeshaking: true
        }
      },
      optimization: {
        minimize: false
      }
    }
  }
});
```

**Comment by IWANABETHATGUY** [comment]
feel free to reopen this issue, if you have any further problem.

**Comment by hverlin** [comment]
@IWANABETHATGUY Thank you, this resolves the issue.
Is it safe to use? I noticed that it got reverted in rsbuild here: https://github.com/web-infra-dev/rsbuild/pull/1875/files

**Comment by IWANABETHATGUY** [comment]
It is almost stable, but if you have any future issues related to `newTreeshaking`, it would be a high priority to fix it .
