### ISSUE TITLE
[Bug]: [Error: nul byte found in provided data at position: 804] { code: 'GenericFailure' }

### ISSUE THREAD

**Issue by elliotwestlake** [web-infra-dev/rspack#6643]
### System Info

  System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 26.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/Library/Caches/fnm_multishells/88287_1716546441488/bin/node
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/88287_1716546441488/bin/npm
    pnpm: 9.1.3 - ~/Library/Caches/fnm_multishells/88287_1716546441488/bin/pnpm
    bun: 1.0.8 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.78
    Safari: 17.1

### Details

elliot@Elliots-MacBook-Pro account % RUST_BACKTRACE=full pnpm build 

> @apps/account@0.1.0 build /Users/elliot/github/apps/apps/account
> rsbuild build

  Rsbuild v0.7.1

● Client ━━━━━━━━━━━━━━━━━━━━━━━━━ (62%) building /Users/elliot/github/apps/node_modules/.pnpm/@rspack+core@0.7.0_@swc+helpers@0.5.3/node_modules/@rspack/core/dist/builtin-plugin/css-extract/loader.js!/Users/elliot/github/apps/node_modules/.pnpm/@rsbuild+core@0.7.1/Federated types extraction completed
● Client ━━━━━━━━━━━━━━━━━━━━━━━━━ (63%) building /Users/elliot/github/apps/node_modules/.pnpm/@rsbuild+core@0.7.1/node_modules/@rsbuild/core/compiled/css-loader/index.js??ruleSet[1].rules[2].use[1]!/Users/elliot/github/apps/node_modules/.pnpm/@rsbuild+core@0.7.1/nodPanic occurred at runtime. Please file an issue on GitHub with the backtrace below: https://github.com/web-infra-dev/rspack/issues
Message:  failed to receive tsfn value: RecvError
Location: /Users/webinfra/ec2-macos-ci-0/_work/rspack/rspack/crates/rspack_napi/src/threadsafe_function.rs:101

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
undefined:0

[Error: nul byte found in provided data at position: 804] {
  code: 'GenericFailure'
}

Node.js v18.17.1
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 1: _napi_register_module_v1
    at <unknown source file>
 2: _napi_register_module_v1
    at <unknown source file>
 3: _napi_register_module_v1
    at <unknown source file>
 4: _napi_register_module_v1
    at <unknown source file>
 5: _napi_register_module_v1
    at <unknown source file>
 6: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 7: _wasmer_vm_imported_memory32_atomic_notify
    at <unknown source file>
 8: _napi_register_module_v1
    at <unknown source file>
 9: _napi_register_module_v1
    at <unknown source file>
10: _napi_register_module_v1
    at <unknown source file>
11: _napi_register_module_v1
    at <unknown source file>
12: _napi_register_module_v1
    at <unknown source file>
13: _napi_register_module_v1
    at <unknown source file>
14: _napi_register_module_v1
    at <unknown source file>
15: _napi_register_module_v1
    at <unknown source file>
16: _napi_register_module_v1
    at <unknown source file>
17: _napi_register_module_v1
    at <unknown source file>
18: _napi_register_module_v1
    at <unknown source file>
19: _napi_register_module_v1
    at <unknown source file>
20: _napi_register_module_v1
    at <unknown source file>
21: __pthread_joiner_wake
    at <unknown source file>
 ELIFECYCLE  Command failed with exit code 129.
elliot@Elliots-MacBook-Pro account % Federated types created correctly
Error: Process 21172 doesn't have open IPC channels
    at /Users/elliot/github/apps/node_modules/.pnpm/@module-federation+dts-plugin@0.1.15_typescript@5.4.5_vue-tsc@1.8.27_typescript@5.4.5_/node_modules/@module-federation/dts-plugin/dist/forkGenerateDts.js:45:9
    at new Promise (<anonymous>)
    at sendMessage (/Users/elliot/github/apps/node_modules/.pnpm/@module-federation+dts-plugin@0.1.15_typescript@5.4.5_vue-tsc@1.8.27_typescript@5.4.5_/node_modules/@module-federation/dts-plugin/dist/forkGenerateDts.js:40:36)
    at process.handleMessage (/Users/elliot/github/apps/node_modules/.pnpm/@module-federation+dts-plugin@0.1.15_typescript@5.4.5_vue-tsc@1.8.27_typescript@5.4.5_/node_modules/@module-federation/dts-plugin/dist/forkGenerateDts.js:76:17)
^A^C

### Reproduce Steps

I was unable to create a reproduction as the error seems to occur when we are using components from our private component library. The component library is built using `vanilla-extract`

**Comment by LingyuCoder** [comment]
Seems to return unicode `\u{0}` in some hook. I tried to insert `\u{0}` in the configuration, hook, and source code to reproduce but failed.

Hard to troubleshoot without reproduction project. So keep this issue open and we will fix it if we can reproduce it

**Comment by elliotwestlake** [comment]
@LingyuCoder I've been able to create a reproduction using [braid-design-system](https://github.com/seek-oss/braid-design-system)

https://github.com/elliotwestlake/rsbuild-v0.7.0-repro/
