### ISSUE TITLE
[Bug]: Cannot get final name for export '__esModule'

### ISSUE THREAD

**Issue by colinaaa** [web-infra-dev/rspack#6871]
### System Info

  System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 6.95 GB / 96.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  npmPackages:
    @rspack/cli: ^0.7.0 => 0.7.4 
    @rspack/core: ^0.7.0 => 0.7.4 

### Details

I have a CommonJS module like this:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
Object.defineProperty(exports, "foo", {
  enumerable: true,
  get: function () {
    return "foo";
  },
});
```

Using Rspack v0.7.4 with Rsbuild v0.7.9 and `concatenatedModules: true` will panic with the following message:

```
Message:  Cannot get final name for export '__esModule'
Location: crates/rspack_core/src/concatenated_module.rs:2136
```

1. Using Rspack v0.7.4 alone is fine.
2. Using Rsbuild v0.7.9 with Rspack v0.7.3 is fine.
3. Removing the `Object.defineProperty(exports, "__esModule", { value: true });` is file.

### Reproduce link

https://github.com/colinaaa/rspack-concatenated-repro

### Reproduce Steps

1. pnpm install
2. pnpm run bulid:rsbuild

Note that `npm run build:rspack` will succeed.

**Comment by xc2** [comment]
## Minimal Reproducing

```js
// rspack config
module.exports = {
  module: {
    rules: [
      {
        test: /\.c?js$/,
// reproducing requirements 1
        type: 'javascript/auto',
      },
    ]
  },
  optimization: {
// reproducing requirements 2
    concatenateModules: true,
  },
  plugins: [
// reproducing requirements 3
    new rspack.CssExtractRspackPlugin(),
  ]
};
```

**Comment by colinaaa** [comment]
Why is it considered as an ESM file?

**Comment by colinaaa** [comment]
Setting it to `type: 'javascript/esm'` only prevents rspack from panic. But the result is not correct:

```
> rspack-repro@1.0.0 build:rspack
> RSPACK=1 pnpm rspack -c ./config.mjs

WARNING in ./src/index.js
  ⚠ HarmonyLinkingWarning: export 'foo' (imported as 'foo') was not found in './foo.cjs' (module has no exports)
   ╭─[1:1]
 1 │ import * as foo from "./foo.cjs";
 2 │
 3 │ console.log(foo.foo);
   ·             ───────
   ╰────


Rspack compiled with 1 warning in 11 ms

rspack-concatenated-repro on  main [!] is 📦 v1.0.0 via  v22.3.0
❯ node rspack-dist/main.js
undefined
```

**Comment by hardfist** [comment]
strict esm use cjs should use import foo from foo.cjs

**Comment by colinaaa** [comment]
With the following configuration:

```
  module: {
    parser: {
      javascript: {
        exportsPresence: 'warn'
      }
    },
    rules: [
      /* config.module.rule('js') */
      {
        test: /\.(?:js|jsx|mjs|cjs|ts|tsx|mts|cts)$/,
        type: 'javascript/esm',
      },
    ]
  },
```

it still not works

```
❯ npm run build:rspack

> rspack-repro@1.0.0 build:rspack
> RSPACK=1 pnpm rspack -c ./config.mjs

WARNING in ./src/index.js
  ⚠ HarmonyLinkingWarning: export 'default' (imported as 'foo') was not found in './foo.cjs' (module has no exports)
   ╭─[1:1]
 1 │ import foo from "./foo.cjs";
 2 │
 3 │ console.log(foo.foo);
   ·             ───────
   ╰────


Rspack compiled with 1 warning in 8 ms

rspack-concatenated-repro on  main [!] is 📦 v1.0.0 via  v22.3.0
❯ node rspack-dist/main.js
/Users/bytedance/rspack-concatenated-repro/rspack-dist/main.js:41
console.log(foo_namespaceObject["default"].foo);
                                           ^

TypeError: Cannot read properties of undefined (reading 'foo')
    at /Users/bytedance/rspack-concatenated-repro/rspack-dist/main.js:41:44
    at Object.<anonymous> (/Users/bytedance/rspack-concatenated-repro/rspack-dist/main.js:43:3)
    at Module._compile (node:internal/modules/cjs/loader:1460:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1544:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1091:12)
    at wrapModuleLoad (node:internal/modules/cjs/loader:212:19)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49

Node.js v22.3.0
```

The output looks like this:

```js
var __webpack_exports__ = {};
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);
// NAMESPACE OBJECT: ./src/foo.cjs
var foo_namespaceObject = {};
__webpack_require__.r(foo_namespaceObject);


;// CONCATENATED MODULE: ./src/foo.cjs

Object.defineProperty(exports, "__esModule", { value: true });
exports.foo = void 0;
Object.defineProperty(exports, "foo", {
  enumerable: true,
  get: function () {
    return "foo";
  },
});

;// CONCATENATED MODULE: ./src/index.js


console.log(foo_namespaceObject["default"].foo);
```

**Comment by colinaaa** [comment]
If I use `javascript/auto` with `import foo from './foo.cjs`, Rspack will panic

**Comment by xc2** [comment]
https://github.com/web-infra-dev/rspack/blob/d73b4fa2ad3dc4740cd7db2bf9b133443a046639/crates/rspack_plugin_extract_css/src/parser_and_generator.rs#L45-L52

@JSerFeng sorry for tagging you, but could you please help with this issue.

I just found that this issue might be related to these lines but not sure. Any reason why `get_concatenation_bailout_reason` is not inherited?

**Comment by dpzxsm** [comment]
Css Module has same waring
```
  ⚠ HarmonyLinkingWarning: export 'default' (imported as 'styles') was not found in './App.module.css' (possible exports: card, logo, logo-spin, react, read-the-docs, root)
    ╭─[6:1]
  6 │ import "./App.css";
  7 │ import styles from './App.module.css';
  8 │ console.log("suming", styles);
    ·                       ──────
  9 │ function App() {
 10 │     _s();
    ╰────

```

**Comment by xc2** [comment]
hi @dpzxsm , parser config for types `css/*` will only take effect when `experiments.css` is `true`.

If you're using `CssExtractRspackPlugin`, please configure css modules with `css-loader`'s options, e.g.,

```js
    {
        test: /\.css$/,
        use: [
          rspack.CssExtractRspackPlugin.loader,
          {
            loader: "css-loader",
            options: {
              modules: {
                auto: true,
                namedExport: false,
              },
            },
          },
        ],
      },
```

**Comment by xc2** [comment]
@colinaaa could you please try @rspack/core `0.7.5-canary-129960e-20240620181737`

**Comment by xc2** [comment]
@colinaaa could you please try rspack 0.7.5-canary-129960e-20240620181737

**Comment by colinaaa** [comment]
`0.7.5-canary-129960e-20240620181737` works well in our project. Thanks!

**Comment by dpzxsm** [comment]
@xc2 experiments.css is true , my rspack's vesion  is 0.7.4  and  I'm not use CssExtractRspackPlugin
