### ISSUE TITLE
[Bug]: workbox-webpack-plugin doesn't work with rspack

### ISSUE THREAD

**Issue by darekdesu** [web-infra-dev/rspack#7427]
### System Info

 System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 66.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.volta/tools/image/node/20.15.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.7.0 - ~/.volta/tools/image/node/20.15.0/bin/npm
    pnpm: 8.14.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.5
  npmPackages:
    @rspack/cli: ^1.0.0-beta.2 => 1.0.0-beta.2 
    @rspack/core: ^1.0.0-beta.2 => 1.0.0-beta.2 

### Details

`workbox-webpack-plugin` doesn't work with rspack while everything is fine with webpack.

Build attempt ends up with 2 errors:

```
ERROR in × Error:   × TypeError: Cannot read properties of undefined (reading 'set')
  │   │     at Object.fn (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/webpack@5.93.0_webpack-cli@5.1.4/node_modules/webpack/lib/EntryPlugin.js:37:37)
  │   │     at SyncHook.callAsyncStageRange (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/@rspack+lite-tapable@1.0.0-beta.2/node_modules/@rspack/lite-tapable/dist/index.js:246:21)
  │   │     at SyncHook.callStageRange (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/@rspack+lite-tapable@1.0.0-beta.2/node_modules/@rspack/lite-tapable/dist/index.js:265:14)
  │   │     at QueriedHook.call (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/@rspack+lite-tapable@1.0.0-beta.2/node_modules/@rspack/lite-tapable/dist/index.js:224:26)
  │   │     at ~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/@rspack+core@1.0.0-beta.2/node_modules/@rspack/core/dist/Compiler.js:570:244
  │   │     at last.function (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/@rspack+core@1.0.0-beta.2/node_modules/@rspack/core/dist/Compiler.js:810:28)
  │   │
  │ 


ERROR in × TypeError: Cannot read properties of undefined (reading 'source')
  │     at InjectManifest.addAssets (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/workbox-webpack-plugin@7.1.0_webpack@5.93.0/node_modules/workbox-webpack-plugin/build/inject-manifest.js:223:39)
  │     at Object.fn (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/workbox-webpack-plugin@7.1.0_webpack@5.93.0/node_modules/workbox-webpack-plugin/build/inject-manifest.js:106:31)
  │     at next (~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/@rspack+lite-tapable@1.0.0-beta.2/node_modules/@rspack/lite-tapable/dist/index.js:492:37)
  │     at ~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/@rspack+lite-tapable@1.0.0-beta.2/node_modules/@rspack/lite-tapable/dist/index.js:521:29
  │     at ~/Projects/Github/rspack-bug-svgo-loader/node_modules/.pnpm/html-webpack-plugin@5.6.0_@rspack+core@1.0.0-beta.2_webpack@5.93.0/node_modules/html-webpack-plugin/index.js:1165:7


2 ERRORS in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

```

### Reproduce link

https://github.com/darekdesu/rspack-bug-workbox

### Reproduce Steps

Run `pnpm install` and then:
- `pnpm run build:webpack` - works 🟢 
- `pnpm run build:rspack` - **doesn't work** 🔴

**Comment by SyMind** [comment]
@darekdesu Use [@aaroon/workbox-rspack-plugin](https://github.com/Clarkkkk/workbox-rspack-plugin) instead
