### ISSUE TITLE
[Bug]: loading CSS files based on manifest.json in federation causes errors

### ISSUE THREAD

**Issue by WillowRyu** [web-infra-dev/rspack#7453]
### System Info

```
 System:
    OS: macOS 14.0
    CPU: (10) x64 Apple M1 Pro
    Memory: 100.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - ~/Library/pnpm/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.20.2/bin/pnpm
    Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 127.0.6533.89
    Edge: 127.0.2651.86
    Safari: 17.0
  npmPackages:
    @rspack/cli: 1.0.0-beta.2 => 1.0.0-beta.2 
    @rspack/core: 1.0.0-beta.2 => 1.0.0-beta.2 
    @rspack/plugin-react-refresh: 1.0.0-beta.2 => 1.0.0-beta.2 
    @module-federation/enhanced": "0.3.3"
    @module-federation/runtime": "0.3.3"
    @module-federation/sdk": "0.3.3"
```

### Details

We are currently using `rspack` with `module-federation/enhanced`.
After updating to version `1.0.0-beta.2`, the following error occurs when loading CSS files from a remote.

When loaded with top level await:

```
TypeError: Cannot read properties of undefined (reading 'call')
undefined factory ./src/test-css.css < remote module
```

When loaded with loadRemote:
```
TypeError: id.startsWith is not a function
    at matchRemoteWithNameAndExpose (main.js:21:34)
    at RemoteHandler.getRemoteModuleAndOptions (main.js:1754:33)
    at async RemoteHandler.loadRemote (main.js:1657:64)
```

This error only appears when loading based on `manifest.json`, and does not occur when loading based on `remoteEntry.js`.
In version `1.0.0-beta.1`, it works well even with `manifest.json`.
Is any additional configuration needed in rspack?

I used the configuration from the rspack-hmr example.
The federation settings for the remote and host are as follows. No separate CSS loader was used.

```
...
 experiments: {
    css: true,
  },
 new ModuleFederationPlugin({
      name: name,
      filename: "remoteEntry.js",
      manifest: true,
      exposes: {
        "./test-css": "./src/test-css.css",
      },
      shared: ["react", "react-dom", "react-router-dom"],
    }),
```

```
...
 experiments: {
    css: true,
  },
new ModuleFederationPlugin({
      name: name,
      filename: "remoteEntry.js",
      manifest: true,
      remotes: {
        app_02: "app_02@http://localhost:3001/mf-manifest.json",
      },
      shared: ["react", "react-dom", "react-router-dom"],
    }),
```

### Reproduce Steps

It occurs when a CSS file is created and exposed in the remote module, 
and the host loads the remote based on the manifest.

I can provide an example if needed.

**Comment by WillowRyu** [comment]
It was my mistake for not including the loader. I will close the issue.
