### ISSUE TITLE
[Bug][DevServer]: `TypeError: Cannot read properties of undefined (reading 'get')` when making network request to compiled asset

### ISSUE THREAD

**Issue by mxmason** [web-infra-dev/rspack#7618]
### System Info

**System:**
 OS: macOS 14.4.1
CPU: (8) arm64 Apple M2
Memory: 70.70 MB / 16.00 GB
 Shell: 5.9 - /bin/zsh
**Binaries:**
Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
pnpm: 8.15.6 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
bun: 1.1.12 - ~/.bun/bin/bun
**npmPackages:**
@rspack/cli: 1.0.0-beta.5 => 1.0.0-beta.5 
@rspack/core: 1.0.0-beta.5 => 1.0.0-beta.5 

### Details

After starting the dev server, it crashes as soon as the browser requests one of its compiled assets.

The crash produces the following error (path truncated for brevity):

```
[...]/node_modules/.pnpm/webpack-dev-middleware@7.4.0_webpack@5.93.0/node_modules/webpack-dev-middleware/dist/utils/getFilenameFromUrl.js:120
        const assetInfo = assetsInfo.get(pathname.slice(publicPathObject.pathname.length));
                                     ^

TypeError: Cannot read properties of undefined (reading 'get')
    at getFilenameFromUrl ([...]/node_modules/.pnpm/webpack-dev-middleware@7.4.0_webpack@5.93.0/node_modules/webpack-dev-middleware/dist/utils/getFilenameFromUrl.js:120:38)
    at processRequest ([...]/node_modules/.pnpm/webpack-dev-middleware@7.4.0_webpack@5.93.0/node_modules/webpack-dev-middleware/dist/middleware.js:393:24)
    at ready ([...]/node_modules/.pnpm/webpack-dev-middleware@7.4.0_webpack@5.93.0/node_modules/webpack-dev-middleware/dist/utils/ready.js:16:5)
    at middleware ([...]/node_modules/.pnpm/webpack-dev-middleware@7.4.0_webpack@5.93.0/node_modules/webpack-dev-middleware/dist/middleware.js:666:5)
    at Layer.handle [as handle_request] ([...]/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix ([...]/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:328:13)
    at [...]/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:286:9
    at Function.process_params ([...]/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:346:12)
    at next ([...]/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/index.js:280:10)
    at compression ([...]/node_modules/.pnpm/compression@1.7.4/node_modules/compression/index.js:220:5)
```

### Reproduce link

https://github.com/mxmason/rspack-repro-dev-crash

### Reproduce Steps

1. run `pnpm i`
2. run `pnpm run dev:rspack`
3. verify that the server _has not crashed yet_
4. navigate to http://localhost:8080
5. verify that the index.html file is returned, but there's no "hello world" from the `main` bundle
6. verify that the dev server has crashed
7. run `pnpm run dev:webpack` and verify that "hello world" _does_ render

> [!NOTE]
> DevServer crashes as soon as the browser requests `main.js`. If you comment out the `plugins` array in `config.mjs`, the server will only crash if you go to `http://localhost:8080/main.js`.

**Comment by h-a-n-a** [comment]
Closed as fixed by upstream: https://github.com/webpack/webpack-dev-middleware/pull/1927

**Comment by mxmason** [comment]
Thanks, @h-a-n-a. It looks like `webpack-dev-middleware@7.4.2` has this fix, but the latest release of rspack doesn't use 7.4.2. Can you say when rspack will upgrade its dependencies?
