### ISSUE TITLE
[Bug]: The source map is not working on Sentry

### ISSUE THREAD

**Issue by cjnoname** [web-infra-dev/rspack#7914]
### System Info

  System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.03 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v22.8.0/bin/npm
    bun: 1.1.27 - /usr/local/bin/bun
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 18.0

### Details

The source maps stopped working on Sentry. After discussing with their team, we identified that the issue was caused by an invalid source map generated by Rspack.

When testing the source map with source-map-explorer or other tools, the following error appeared:

'Your source map refers to generated column 53099 on line 39, but the source only contains 53098 columns on that line. Please verify that you are using the correct source map.'

Approximately 70% of the source map files we tested are working, while 30% have failed.

### Reproduce Steps

https://github.com/cjnoname/rspack-reproduce

npm run s

**Comment by hardfist** [comment]
please provide rspack version

**Comment by cjnoname** [comment]
> please provide rspack version

1.0.5 the latest

**Comment by cjnoname** [comment]
> please provide rspack version

I could send you the buggy soucemap files and mjs files via email or whatever tools but I don't want to share them with public.

**Comment by gitim** [comment]
I think this is the same issue as https://github.com/web-infra-dev/rspack/pull/7647. we found that source map stopped generated properly since 1.0.1 version. @cjnoname, you can try the 1.0.0 version of rspack to identify when it was broken.

**Comment by gitim** [comment]
I think this is the same issue as https://github.com/web-infra-dev/rsbuild/issues/3433 we found that source map stopped generated properly since 1.0.1 version. @cjnoname, you can try the 1.0.0 version of rspack to identify when it was broken.

**Comment by cjnoname** [comment]
@hardfist 

This is a significant issue since Sentry is the primary monitoring tool for many companies, and I hope someone can assist in looking into it.

Verifying the issue is straightforward - a single command line should work:

npx source-map-explorer index.mjs index.mjs.map

**Comment by hardfist** [comment]
> @hardfist
> 
> This is a significant issue since Sentry is the primary monitoring tool for many companies, and I hope someone can assist in looking into it.
> 
> Verifying the issue is straightforward - a single command line should work:
> 
> npx source-map-explorer index.mjs index.mjs.map

I can't investigate more without any reproductions

**Comment by cjnoname** [comment]
> > @hardfist
> > This is a significant issue since Sentry is the primary monitoring tool for many companies, and I hope someone can assist in looking into it.
> > Verifying the issue is straightforward - a single command line should work:
> > npx source-map-explorer index.mjs index.mjs.map
> 
> @cjnoname I can't investigate more without any reproductions, maybe you should try upgrade to 1.0.5 to see whether the sourcemap problem is solved

https://github.com/cjnoname/rspack-reproduce

You can find the issue with a simple command: "npm run s".

I am not sure if this is the only issue causing the sourcemap to break, or if there might be other issues as well.

**Comment by yuzhva** [comment]
> maybe you should try upgrade to 1.0.5 to see whether the sourcemap problem is solved

Hey hi, guys 👋 

Would like to confirm that the latest v1.0.5 has a broken source map.

We upgraded from 0.7.5 to 1.0.3 and noticed an issue with the broken source-map - there is a big % of `[no source]` code based on `source-map-explorer` package analyse.
(NOTE: you need to run the package with `--no-border-checks` key to process the broken source maps completely, e.g: `npx source-map-explorer --no-border-checks ./dist`)

So we downgraded all `@rspack` package to stable `v1.0.0`

**Comment by hardfist** [comment]
@yuzhva @cjnoname sorry for the inconvenience and reproduction, confirmed it's a bug we are gonna fix it ASAP.

**Comment by cjnoname** [comment]
> @yuzhva @cjnoname sorry for the inconvenience and reproduction, confirmed it's a bug we are gonna fix it ASAP.

I’ve put together a minimal reproduction repository last night. While I haven't done something exactly like this before, it should accurately represent the issue.

https://github.com/cjnoname/rspack-reproduce

Not sure if it's the only issue on sourcemap or not.

**Comment by SyMind** [comment]
I am currently investigating this issue.

**Comment by SyMind** [comment]
@cjnoname Currently, it looks like the issue with the source map is caused by the `swc` minifier. Please use the [Terser Webpack Plugin](https://webpack.js.org/plugins/terser-webpack-plugin/) to handle code minification first.

If the issue persists, there may be other factors causing the source map generation error. Please provide additional repos to reproduce the problem.

**Comment by SyMind** [comment]
In this repository, you can observe that the source maps generated by SWC cause errors in source-map-explorer.
https://github.com/SyMind/swc-minifier-source-map-bug

**Comment by cjnoname** [comment]
> In this repository, you can observe that the source maps generated by SWC cause errors in source-map-explorer. https://github.com/SyMind/swc-minifier-source-map-bug

Thank you for investigating this issue. I understand that the SWC minifier is also maintained by your team, correct?

Could you let us know if there are any plans to address this issue in the near future? We are willing to wait a few days if necessary.

We are experiencing poor performance with the Terser Webpack Plugin, which we would prefer not to revert to.

Do you have an estimated timeline for a fix?

Thanks

**Comment by SyMind** [comment]
@cjnoname I'm not certain if the issue is actually caused by the SWC minifier. Could you please try using the Terser Webpack Plugin and see if the problem persists?

**Comment by SyMind** [comment]
@yuzhva Please provide the a demo to reproduce the issue.

**Comment by cjnoname** [comment]
> @cjnoname I'm not certain if the issue is actually caused by the SWC minifier. Could you please try using the Terser Webpack Plugin and see if the problem persists?

The issue persists even after I turned off the minimizer and disabled output: module. It still occurs. You can easily check it in my repo by adjusting the rspack.config.js file.

**Comment by SyMind** [comment]
@cjnoname You can see the code in source-map-explorer here: https://github.com/danvk/source-map-explorer/blob/master/src/lib/explore.ts#L208

**Comment by cjnoname** [comment]
> @cjnoname You can see the code in source-map-explorer here: https://github.com/danvk/source-map-explorer/blob/master/src/lib/explore.ts#L208

It works, but it's running much slower than before. Could you help me report this issue to SWC?

**Comment by SyMind** [comment]
@cjnoname Yes. If you can confirm that the issue is caused by the SWC minifier, I will continue to work on it.

**Comment by cjnoname** [comment]
> @cjnoname Yes. If you can confirm that the issue is caused by the SWC minifier, I will continue to work on it.

Yeah... Terser Webpack Plugin works fine for now. Please go ahead.

**Comment by yuzhva** [comment]
Here is a fork with an example for source-map "investigation":

https://github.com/yuzhva/rspack-repro

I just forked the original repo `https://github.com/web-infra-dev/rspack-repro` and enabled the source map for `rsbuild.config.ts` and `rspack.config.mjs` configs:

Results of Source Map investigation just open:
For v1.0.5:
- webpack: [./webpack-dist-v105/webpack-dist_main.js-Source_Map_Explorer.html](https://htmlpreview.github.io/?https://github.com/yuzhva/rspack-repro/blob/main/webpack-dist-v105/webpack-dist_main.js-Source_Map_Explorer.html)
- rspack: [./rspack-dist-v105/rspack-dist-v105_main.js-Source_Map_Explorer.html](https://htmlpreview.github.io/?https://github.com/yuzhva/rspack-repro/blob/main/rspack-dist-v105/rspack-dist-v105_main.js-Source_Map_Explorer.html)
- rsbuil: [./rsbuild-dist-v105/rsbuild-dist-v105_static_js_index.1a9c415f.js-Source_Map_Explorer.html](https://htmlpreview.github.io/?https://github.com/yuzhva/rspack-repro/blob/main/rsbuild-dist-v105/rsbuild-dist-v105_static_js_index.1a9c415f.js-Source_Map_Explorer.html)

**Comment by yuzhva** [comment]
@SyMind 
cc: @cjnoname 

I can confirm that the root cause is in `swc` minifiyer.

Source Map works with one of the next configs:
1. disable modifications:
```json
optimization: {
  minimize: false,
},
```

2. pass empty array as `minimizer` key for config:
```json
optimization: {
  minimize: true,
  minimizer: [],
},
```

3. Or use the Terser Webpack Plugin:
```json
const TerserPlugin = require("terser-webpack-plugin");

optimization: {
  minimize: true,
  minimizer: [new TerserPlugin()],
},
```

The Terser - is extremely slow.

---

Our current configuration right now (which does not work):
```json
const { SwcJsMinimizerRspackPlugin } = require('@rspack/core');

optimization: {
  minimize: true,
  minimizer: [new SwcJsMinimizerRspackPlugin()],
},
```

**Comment by ckken** [comment]
same here

**Comment by mmazzarolo** [comment]
Looks like SWC fixed the issue, thanks @SyMind for posting it there! Out of curiosity, how does the rsbuild release process look like for downstream dependency updates (such as SWC)?

**Comment by hardfist** [comment]
> Looks like SWC fixed the issue, thanks @SyMind for posting it there! Out of curiosity, how does the rsbuild release process look like for downstream dependency updates (such as SWC)?

normally we bump swc version in minor release, but if it contains hotfix bug, we may release early

**Comment by cjnoname** [comment]
> > Looks like SWC fixed the issue, thanks @SyMind for posting it there! Out of curiosity, how does the rsbuild release process look like for downstream dependency updates (such as SWC)?
> 
> normally we bump swc version in minor release, but if it contains hotfix bug, we may release early

Any plan to release a new version soon?

**Comment by cjnoname** [comment]
> @cjnoname it's already available in `1.0.7`

Nope

**Comment by mmazzarolo** [comment]
Ouch. You're right. My B.

**Comment by cjnoname** [comment]
Seems like this SWC version is buggy

https://github.com/swc-project/swc/issues/9592

**Comment by 9aoy** [comment]
> Seems like this SWC version is buggy 

@cjnoname  Thanks for your reminder 🌹  . Rspack currently does not use the functions related to this issue. If there are any problems in the future, we will follow up in time.

And it's already available in [1.0.8](https://github.com/web-infra-dev/rspack/releases/tag/v1.0.8).

**Comment by cjnoname** [comment]
> > Seems like this SWC version is buggy
> 
> @cjnoname Thanks for your reminder 🌹 . Rspack currently does not use the functions related to this issue. If there are any problems in the future, we will follow up in time.
> 
> And it's already available in [1.0.8](https://github.com/web-infra-dev/rspack/releases/tag/v1.0.8).

This is awesome. Much appreciated!

**Comment by cjnoname** [comment]
> @cjnoname Yes. If you can confirm that the issue is caused by the SWC minifier, I will continue to work on it.

Hi mate, it's still not working... due to a different issue. Please refer to the same repo to reproduce.

https://github.com/cjnoname/rspack-reproduce

Thanks.

**Comment by ckken** [comment]
> ![image](https://private-user-images.githubusercontent.com/3890513/371980985-4c4ef547-ef0e-4bcd-b84c-f15c26b9621d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODA0MDEsIm5iZiI6MTcyNzY4MDEwMSwicGF0aCI6Ii8zODkwNTEzLzM3MTk4MDk4NS00YzRlZjU0Ny1lZjBlLTRiY2QtYjg0Yy1mMTVjMjZiOTYyMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDcwODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI3N2E3ZGQwZTQ3ZDA4YjBjMDQ4M2MwODU3YWFiMWRiODI0ZWFmNzhhMWE2ODExMTA1YTMwMzZjNmIyZWVhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gF67h9JSPIpPcgXkS5H1CQG2p5defwQdKDtIxmbCNYs) 1.0.8

devtool: 'source-map'

**Comment by mmazzarolo** [comment]
I can confirm the issue is still there in `1.0.10`. Just like before, `source-map` is broken, `cheap-module-source-map` works fine. I see the issue is being discussed in other threads (e.g., https://github.com/web-infra-dev/rspack/issues/8021), is there an official issue tracking this bug and do we know if it's SWC or rspack/rsbuild-related? Is there any workaround besides downgrading to Rspack `1.0.0`?

**Comment by powerfulj** [comment]
This is actually a serious bug that prevents people from using Rspack normally. I hope someone can fix it soon so Rspack can return to normal use.

**Comment by SyMind** [comment]
Today, I checked and found that the issue with SWC still exists. Previously, I upgraded SWC and did some local testing. It might be because I modified the source-map-explorer code, which led me to mistakenly believe that the issue with SWC had been fixed.

I will continue working to resolve this issue.

**Comment by cjnoname** [comment]
> Today, I checked and found that the issue with SWC still exists. Previously, I upgraded SWC and did some local testing. It might be because I modified the `source-map-explorer` code, which led me to mistakenly believe that the issue with SWC had been fixed.
> 
> I will continue working to resolve this issue.

Thanks for fixing the previous issue with Sentry—it worked as expected. However, there's a different issue with some other packages that I'm quite certain about. I'm also a bit concerned there might be additional issues now that the original one has been resolved.

**Comment by SyMind** [comment]
@cjnoname I've released a canary version of Rspack 1.0.9-canary-5f4b3e7d-20241010033454. Could you please verify if it works correctly? Thank you!

**Comment by cjnoname** [comment]
> [@cjnoname](https://github.com/cjnoname) I've released a canary version of Rspack `1.0.9-canary-5f4b3e7d-20241010033454`. Could you please verify if it works correctly? Thank you!

Hey mate, I could not find your version

**Comment by SyMind** [comment]
@cjnoname Please use the following package to replace `@rspack/core`: https://www.npmjs.com/package/@rspack/core-canary/v/1.0.9-canary-5f4b3e7d-20241010033454. Update your dependencies as shown below:

```json
"@rspack/core": "npm:@rspack/core-canary@1.0.9-canary-5f4b3e7d-20241010033454"
```

**Comment by cjnoname** [comment]
> [@cjnoname](https://github.com/cjnoname) Please use the following package to replace `@rspack/core`: https://www.npmjs.com/package/@rspack/core-canary/v/1.0.9-canary-5f4b3e7d-20241010033454. Update your dependencies as shown below:
> 
> "@rspack/core": "npm:@rspack/core-canary@1.0.9-canary-5f4b3e7d-20241010033454"

It works mate, thank you

**Comment by mmazzarolo** [comment]
@SyMind how about us folks using Rsbuild 👼 ?

**Comment by mmazzarolo** [comment]
This change is included in `rsbuild@1.0.12`, right? (I see it includes `rspack@1.0.9`). For what is worth, it's still not working for us 😿 

Ton of sourcemaps area are unreachable and can't be debugger. Downgrading Rsbuild (a lot) fixes it. I'll try to investigate a bit more, but  I'm a bit lost at the moment.

![Image](https://github.com/user-attachments/assets/bc9c311e-ce06-4757-9373-0075f3d2cc03)

**Comment by inottn** [comment]
> [@SyMind](https://github.com/SyMind) what about us folks using Rsbuild 👼 ? Will this be included in the next release?

rspack@1.0.9 does not include this change, but it should be included in the next version.

**Comment by cjnoname** [comment]
Can we release it as soon as possible? You wouldn't want to see a bundling tool that doesn't support source maps, right? :)

**Comment by SyMind** [comment]
@mmazzarolo To override `@rspack/core`, use the following configuration. This will include the next version:

```json
"@rspack/core": "npm:@rspack/core-canary@1.0.9-canary-5f4b3e7d-20241010033454"
```

**Comment by SyMind** [comment]
@cjnoname I will release a new version today.

**Comment by mmazzarolo** [comment]
> [@mmazzarolo](https://github.com/mmazzarolo) To override `@rspack/core`, use the following configuration. This will include the next version:
> 
> "@rspack/core": "npm:@rspack/core-canary@1.0.9-canary-5f4b3e7d-20241010033454"

I'm on rsbuild so the process is a bit different but good to know, thanks! Thought it was released because I saw the issue being closed :)

**Comment by SyMind** [comment]
@cjnoname I have released the 1.0.10 version https://github.com/web-infra-dev/rspack/releases/tag/v1.0.10

**Comment by yuzhva** [comment]
In `1.0.10` version source maps have been restored for 27.4% for our project - it's still better than having 100% of broken source maps.

It's a bit hard to debug to understand what exactly part of the code does not receive generated source maps: the app code, .mjs modules, or something else 🤷 

Will try to debug it more to understand which parts of source maps are missing...

**Comment by SyMind** [comment]
@mmazzarolo can you give me a reproduce.

**Comment by mmazzarolo** [comment]
I've been trying, but I can't produce a "minimal" reproducible example 😔. Out production codebase is pretty big and as @yuzhva mentioned it's hard to determine what's causing the issue and putting it into a minimal reproducible example. I tried using same RSBuild config and some similar npm packages for example, but with no success. 
The only thing I can confirm is that our issues have been introduced in https://github.com/web-infra-dev/rspack/releases/tag/v1.0.1 (I assume it's from https://github.com/web-infra-dev/rspack/pull/7647) — if we revert to a version of rsbuild that depends on `1.0.0` everything works fine (we're basically stuck in this state since our app is otherwise unusable without working sourcemaps).

**Comment by SyMind** [comment]
I will release a new version for rspack today to fix this issue.

**Comment by SyMind** [comment]
@mmazzarolo I've released a canary version of Rspack `@rspack/core-canary@1.0.12-canary-80db131b-20241016051915`. Could you please verify if it works correctly? Thank you!

To override `@rspack/core`, use the following configuration:

"@rspack/core": "npm:@rspack/core-canary@1.0.12-canary-80db131b-20241016051915"

**Comment by mmazzarolo** [comment]
@SyMind thanks for looking into ti!

I assume you mean to add it as an override/resolution, right?

So adding:

```json
  "resolutions": {
    "@rspack/core": "npm:@rspack/core-canary@1.0.12-canary-80db131b-20241016051915"
  },
```

If I do that, the install step (using `pnpm i`) goes fine, but building fails:

```
  Rsbuild v1.0.14

error   Failed to build.
error   Unmatched version @rspack/core@1.0.11, @rspack/binding@1.0.12-canary-80db131b-20241016051915, @rspack/binding-darwin-arm64@1.0.12-canary-80db131b-20241016051915
    at checkVersion (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/core/dist/index.js:16986:21)
    at #getInstance (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/core/dist/index.js:17488:19)
    at #build (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/core/dist/index.js:17412:22)
    at /Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/core/dist/index.js:17384:18
    at done (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/lite-tapable/dist/index.js:473:13)
    at AsyncSeriesHook.callAsyncStageRange (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/lite-tapable/dist/index.js:480:20)
    at AsyncSeriesHook.callAsync (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/lite-tapable/dist/index.js:82:21)
    at _Compiler.compile (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/core/dist/index.js:17378:30)
    at /Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/core/dist/index.js:17240:16
    at done (/Users/matteo.mazzarolo/workspace/TTVPlatform/node_modules/@rspack/lite-tapable/dist/index.js:473:13)
/Users/matteo.mazzarolo/workspace/TTVPlatform/apps/studio:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @synthesia/studio@1.4.0 build: `./scripts/build-app-with-rsbuild.sh`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

Not sure why. Pinning specific versions of `@rspack/core` has worked for me before, though. Just not this one.

**Comment by hmdoganjf** [comment]
I'm having the same problem with Sentry sourcemaps, and I think this canary build does not work with @rspack/cli. I keep having unmatched version error, and following the dist code I think @rspack/core thinks its on version 1.0.11, while bindings give the canary version.

```[rspack-cli] Error: Unmatched version @rspack/core@1.0.11, @rspack/binding@1.0.12-canary-80db131b-20241016051915, @rspack/binding-darwin-arm64@1.0.12-canary-80db131b-20241016051915```

![Image](https://github.com/user-attachments/assets/75e1902a-61dc-42ea-b3d8-aa7973cd12d5)

**Comment by mmazzarolo** [comment]
@SyMind was the fix shipped with `@rspack/core@1.0.12`? Asked because i tried forcing it as a resolution to use it with `rsbuild` and the issue is still there for us.

**Comment by hmdoganjf** [comment]
Can confirm, issue is not resolved on 1.0.12. I guess we will have to wait until the next release.

**Comment by hmdoganjf** [comment]
Yes! It seems resolved, I can see the sourcemaps on sentry. Thank you for your help.

**Comment by yuzhva** [comment]
> In `1.0.10` version source maps have been restored for 27.4% for our project - it's still better than having 100% of broken source maps.

In `v1.0.13` source maps are resolved for 77.6%

Here are screenshots:

...

**Comment by cjnoname** [comment]
> > In `1.0.10` version source maps have been restored for 27.4% for our project - it's still better than having 100% of broken source maps.
> 
> In `v1.0.13` source maps are resolved for 77.6%
> 
> **NOTE: the same amount of source maps was broken in `v0.7.5`, so it seems to be an old issue, which is not related to the update to v.1**
> 
> Here are screenshots:
> 
> `v1.0.10` - **27.2%** of source maps are works: ![Image](https://github.com/user-attachments/assets/b1299d00-442e-4a67-817f-6b9b32b06286)
> 
> `v1.0.13`: - **77.6%** of source maps are works: ![Image](https://github.com/user-attachments/assets/95e8a39d-e098-4d76-aefa-7c92f06201b6)
> 
> `TerserPlugin` plugin resolves 100% of source maps: ![Image](https://github.com/user-attachments/assets/0fdfcc10-4ea2-45ff-a713-f7572bdcbb9b)
> 
> It seems that:
> 
> * 11.2% of broken source maps are still in node_modules
> * another 11.2% of broken source maps are still in coudebase

How about the RC version mate, was it 100%?

**Comment by mmazzarolo** [comment]
Thanks @SyMind 🙏 This seems to be fixing the issues so far. But we'll need a bit more time to do a complete check.

@cjnoname my understanding from @yuzhva is that the current version (the one with the fix) has a coverage of 77.6% for him. But the coverage with rspack/swc might have never been 100% (even before 1.0.1, which we suspected being the version that introduced the issue).
TerserPlugin does provide a complete coverage though... it would be interesting to understand why we can't do that with rspack/swc.

**Comment by cjnoname** [comment]
Hey guys, I can confirm that the source map is inaccurate, especially as it shows errors on the wrong lines of code.

**Comment by hardfist** [comment]
> Thanks [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/19852293?s=64&amp;u=deb4053c0d16957959f3fdf41fe208a1f8baaa1a&amp;v=4">@SyMind](https://github.com/SyMind) 🙏 This seems to be fixing the issues so far. But we'll need a bit more time to do a complete check.
> 
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/29768744?s=64&amp;u=8edefdbfd1061599945ac0bf440bfc4ea98edf1b&amp;v=4">@cjnoname](https://github.com/cjnoname) my understanding from [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/yuzhva?size=32">@yuzhva](https://github.com/yuzhva) is that the current version (the one with the fix) has a coverage of 77.6% for him. But the coverage with rspack/swc might have never been 100% (even before 1.0.1, which we suspected being the version that introduced the issue). TerserPlugin does provide a complete coverage though... it would be interesting to understand why we can't do that with rspack/swc.

if terserPlugin provides complete coverage and swc don't provide, then it's normally a swc minifier bug, we may need more information to investigate swc minifier problem

**Comment by SyMind** [comment]
I will continue to make efforts on the SWC minifier, trying to bring it to 100%. However, this process might be quite slow.

**Comment by SyMind** [comment]
@yuzhva can you give me a reproduce repo?

**Comment by yuzhva** [comment]
> How about the RC version mate, was it 100%?

I just checked the v1.2.3 - there is no difference compared to improvements in v1.0.13

`v1.2.3`: - 77.6% of source maps are works:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/3402fcb1-62fc-412e-aca2-4be116800e0f" />

`TerserPlugin` plugin resolves 100% of source maps:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/415be7c6-26a6-4d16-976a-1489465439b7" />

---
Will try to find some time to prepare repo with example on where it would be possible to reproduce the bug
