### ISSUE TITLE
[Bug]: rspack serve cannot complete execution after using ModuleFederationPlugin

### ISSUE THREAD

**Issue by doerme** [web-infra-dev/rspack#8103]
### System Info

OS: macOS 15.0.1
CPU: 2.2 GHz 六核Intel Core i7
Memory: 16 GB 2400 MHz DDR4
Shell: git bash
Binaries:
Node: 20.11.1

### Details

![Image](https://github.com/user-attachments/assets/a343bace-71ba-4a44-bbb1-72f2dc350b0a)

pnpm dev will be block

### Reproduce link

https://github.com/empjs/rspack-q-and-A/tree/main/projects/runtime_demo/host

### Reproduce Steps

pnpm i
pnpm dev

**Comment by doerme** [comment]
dev version:

@rspack/cli@1.0.10
@rspack/core@1.0.10
@module-federation/enhanced@0.6.10

**Comment by LingyuCoder** [comment]
Caused by this error which is threw by ModuleFederationPlugin:

```js
Error: [ ModuleFederationPlugin ]: name is required
    at ModuleFederationPlugin.apply (/Users/bytedance/rspack-dev/repro/rspack-q-and-A/node_modules/.pnpm/@module-federation+rspack@0.6.10_typescript@5.5.4/node_modules/@module-federation/rspack/dist/index.cjs.js:128:27)
    at createCompiler (/Users/bytedance/rspack-dev/rspack/packages/rspack/dist/index.js:23228:17)
    at create3 (/Users/bytedance/rspack-dev/rspack/packages/rspack/dist/index.js:23261:22)
    at rspack2 (/Users/bytedance/rspack-dev/rspack/packages/rspack/dist/index.js:23284:41)
    at RspackCLI.createCompiler (/Users/bytedance/rspack-dev/rspack/packages/rspack-cli/dist/index.js:740:41)
    at async Object.handler (/Users/bytedance/rspack-dev/rspack/packages/rspack-cli/dist/index.js:585:30)
```

The `@rspack/cli` only handle the validation error but this error is a custom error, so the output is not diplayed. I will try to fix this.
